### ISSUE TITLE
Invalid validator nodes

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony-ops#114]
Per @rlan35 and @LeoHChen, the mainnet routinely sees Pangaea nodes.  Segregate P2P topical groups so that P2P messages sent from a node in one network is not processed by other nodes in another network, and deprecate the legacy group IDs without an embedded network ID.

Deprecation is done over three phases delineated by two epochs.  In all phases, upgraded nodes send/receive consensus messages to/from the new (network-specific) group, but they gradually stop sending to/receiving from the old (network-neutral) group:

| Phase | Duration | Join/process Legacy | Send To Legacy | Notes |
| :--: | :--: | :--: | :--: | :-- |
| 1 | ~3d (2 epochs) | Yes | Yes | New nodes double-process messages from fellow new nodes.  It also allows for cross-shard messages to be exchanged in both directions (old to new and new to old).  During this period, consensus message traffic will be roughly doubled. |
| 2 | ~3d (2 epochs) | Yes | No | Old nodes no longer receive consensus messages from new nodes.  If an old node is the leader, it will fail to collect Prepare/Commit signatures from the supermajority (who sends their messages only to the new group), so view change will occur.  Cross-shard messages from old nodes in another shard still in phase 1 continue to be processed normally. |
| 3 | Forever | No | No | Old nodes are completely ignored and no longer see new blocks.  They act as if they have been severed from the network, e.g. they initiate (futile) view changes.  Cross-shard messages from old nodes get ignored.  Crosstalks between networks stop at this point, and full network isolation at the protocol level is achieved. |

Phase 1 is the grace period for node operators so that they can upgrade to the new version without losing reward.  It should be long enough for most node operators to upgrade.

Phase 2 is the grace period to allow for cross-shard messages from another shard still in phase 1.  It should be long enough to allow for all shards to be in it before any shard moves into phase 3.

Phase 3 is the final phase.

**Comment by harmony-ek** [comment]
Requesting review by @rlan35 @LeoHChen @johnwhitton.

**Comment by LeoHChen** [comment]
what do you mean by cross-shard messages here?  old-to-new? in phase 1, what's the impact to the consensus block time?  all of harmony's nodes be upgraded to the "new nodes" anyway.  I don't know why we need phase 2. We can leave phase 1 long enough for everyone to upgrade to new node and jump to phase 3 directly.

**Comment by harmony-ek** [comment]
> what do you mean by cross-shard messages here? old-to-new? in phase 1, what's the impact to the consensus block time? all of harmony's nodes be upgraded to the "new nodes" anyway. I don't know why we need phase 2. We can leave phase 1 long enough for everyone to upgrade to new node and jump to phase 3 directly.

Phase 2 exists to account for different shards advancing at different times.  Without phase 2, if one shard X moves into phase 3 while another shard Y is still in phase 1, cross-shard transaction from Y to X may break because there is a chance that the randomly chosen senders of CX receipts may be old nodes.

**Comment by LeoHChen** [comment]
If we do not require multiple rolling update with this change, I am okay with the design to avoid cx issue.

**Comment by rlan35** [comment]
This solution of piggybacking on the groupID seems hacky to me. Ethereum has the NetworkID concept to avoid different network's nodes to connect in the handshake phase (https://github.com/ethereum/go-ethereum/blob/master/les/peer.go#L671). Can we do similar thing on the node-level, rather than p2p protocol level?

**Comment by harmony-ek** [comment]
If we want to reject peers during initial connection handshake, it *has* to be done at the P2P level, with a custom protector (`"github.com/libp2p/go-libp2p-core/pnet".Protector`, passed in as a libp2p host option) that can enforce such a handshake.  But network ID handshake at this phase is not backward compatible: A legacy node immediately not using a protector starts encryption handshake (a call of `u.setupSecurity` in `"github.com/libp2p/go-libp2p-transport-upgrader".(*Upgrader).upgrade` function), whereas a protector-enabled node would perform protection handshake first.  That is, the upgrade procedure offers no protocol-level overall handshake that negotiates availability of protector, so a protector cannot be made optional.

**Comment by LeoHChen** [comment]
I was also thinking to speed up the process of adopting the new groupID.  We may just do a rolling update and restart the entire network with FN runners.  SO that we can make it quickly and potentially reduce the risk of the increasing/double network traffic that may slow down the block time, which we had a lot of complaint from FN runners already.  We can propose two solutions to the FN runners and get some opinion from them.
