### ISSUE TITLE
Recover an Offline Node - Sep 17, 2019

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#116]
https://harmonyone.pagerduty.com/incidents/PF22Y0R

**Comment by AndyBoWu** [comment]
`{"level":"warn","port":"9000","ip":"52.32.215.173","hash":"0xbed7d0fe3c9d4e6a3147d3a01e2f44b2f9837b142c1cc07016fa92466a8458bc","caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:284","time":"2019-09-17T16:48:15.105567054Z","message":"Head block missing, resetting chain"}
{"level":"warn","port":"9000","ip":"52.32.215.173","target":0,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/core/blockchain.go:352","time":"2019-09-17T16:48:15.105710987Z","message":"Rewinding blockchain"}`

**Comment by LeoHChen** [comment]
duplication of https://github.com/harmony-one/harmony/issues/1607

**Comment by AndyBoWu** [comment]
Related to https://github.com/harmony-one/harmony/issues/1607
