### ISSUE TITLE
Monitor RAM usage for each node

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#126]
**DESC**
one of the tasks in the DevOps Hackathon is to monitor the RAM usage for each node. See the attached screenshot.

**PRIORITY**
low

![Screen Shot 2019-09-19 at 4 26 31 PM](https://user-images.githubusercontent.com/5258417/65288184-c6976300-dafa-11e9-865d-2ca9e41ac8ab.png)

The occupied memory is around 98%, but the actual memory usage is around 10%. Memory might not be a concern for us.

**Comment by LeoHChen** [comment]
please set some alarm if memory usage is about 80%
-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>
