### ISSUE TITLE
handle all the retirement instances

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#132]
retirement notice in the attachment.

<img width="1440" alt="Screen Shot 2019-09-22 at 5 15 09 PM" src="https://user-images.githubusercontent.com/4513927/65396594-aff04680-dd5c-11e9-8ae9-c91a9c8c10ba.png">

The instruction can be found in "Terraform Node Recovery" section of the runbook.
https://app.gitbook.com/@harmony-one/s/onboarding-wiki/devops-run-book/runbook

Noted, the retirement nodes have to be taken down one by one and launch new TF node one by one.  You can't do all of them at the same time, otherwise, we may facing less number of validators.

Please do it in 3 days.

**Comment by LeoHChen** [comment]
I've handled the retirement one on Sep. 25th.

**Comment by AndyBoWu** [comment]
1-BETA-spot-2019-09-11_00_50_18 | i-0c46df25c7b4865a5
