### ISSUE TITLE
[watchdog] Incorrect Consensus Status for Testnet (Likely mainnet too)

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#151]
Shad 0 and 1 in the testnet are offline, but their status still shows online, and consensus reached. See the attached screenshot.

<img width="1352" alt="Screen Shot 2019-10-06 at 9 49 26 AM" src="https://user-images.githubusercontent.com/5258417/66272450-ae278800-e81e-11e9-996c-0f13bb3e1f95.png">

**Comment by fxfactorial** [comment]
Done.

`distribution_config.txt` no longer used, Leo gave me new one: `BETA.nodes.txt`

Steps to update: 

1. Change watchdog ssh machine's `harmony-ops/monitoring/daemons/monitor-testnet.yaml` file, 
the `machine-ip-list`, 

```yaml
node-distribution:
  machine-ip-list: /home/ec2-user/harmony-ops/monitoring/daemons/BETA.nodes.txt
```

2. sudo systemctl restart harmony-watchdog@testnet


<img width="1275" alt="Screen Shot 2019-10-06 at 3 18 15 PM" src="https://user-images.githubusercontent.com/3036816/66276974-d1692c00-e84c-11e9-87a2-1276d40b2b5d.png">
