### ISSUE TITLE
Less than expected Earning in Shard 0

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#161]
Reported by @yellowsin in #foundation-nodes channel, the earning of some nodes in shard 0 are less than expected.

`
one1ssppn7nu98v6f9us8hzqmxe9x224x4e7g8yrn9: 5.2658
one12xfkkmqm7cnv52tml8vpdawvax0kr8f4wrlp96: 4.68338
one1ffff4d9eaezg8xft30m6n62xfpllah03kvpzdt: 4.11504
one17nacqwrnwgq7pk8eehn7j6jphxt0draqpkztpf: 3.74482
one1yeay879a7dln5ltnchytx8eennpz332qn7yjx3: 3.55428
one1f0yvhlqc5z7v5w5fnk7x7t38tuvjefnyyw258l: 3.31393
one1fuhwmxdr4zulfm0lxndp7lgrstrmfpdam0w7x9: 3.29933
one16jvl43d059a4wpderqu82wlm7t3qzw8yta3wgn: 3.17416
one1s4604lg40q9tvzaaf3wp9rtr3txzl2796p6dgf: 3.10803
one12vyznqd6lz6wwr9gkvd6q5zy9sswx792dh2eyv: 3.07675
one1p6gqsxydrjdflw9ynksvale8dtzdj5neskyw20: 2.93337
one10p09fugsgse0wl0vwglckw20243tzgx33g0stw: 2.65099
one1hxqhp9tls9r4v5hz208g93exhvz5ak258ut7d2: 2.57265
one1s3dx73sa5dzrksmds5recptale8pxsa4d4hzt4: 2.47674
one1ux3gysrzuzcwpv6kz9g26q55fpnm46gs3uca3f: 2.25607
one1mgwlvj9uq365vvndqh0nwrkqac7cgep2pcn6zl: 1.99196
one1737c59mjlcrzswzw79w65xxjg7tm5pyn6jwsju: 1.82059
one1ygq5gu7vtgfff65mcqvhsjxpadrygwc25k37zx: 1.47007
one16m5r7awa4y2z2cyage4cns4uejxx8rn0gw77ug: 0.665793
`

**Comment by AndyBoWu** [comment]
Checked out our internal nodes on each shard, currently, there are a few nodes in shard 3 that are earning less than expected amount. Doing investigation.

**Comment by AndyBoWu** [comment]
TROUBLESHOOTING
*

**Comment by AndyBoWu** [comment]
on this node: 54.70.19.206

`
{"level":"warn","port":"9000","ip":"54.70.19.206","error":"unknown ancestor","inChain":"1028418","MsgBlockNum":"1028420","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:214","time":"2019-10-11T17:58:18.288332606Z","message":"[OnAnnounce] Block content is not verified successfully"}
{"level":"debug","port":"9000","ip":"54.70.19.206","Version":"Harmony (C) 2019. harmony, version v4044-r3-20190827.0-0-g0a4f4f8f (jenkins@ 2019-08-28T03:57:12+0000)","BlsKey":"783841b0eaea497e2f894d482b6bde16b96359cb837a9f7dc3bf89abcb45b75e8ea597d60d2e89775c6fb37164fa3694","IP":"13.236.118.50","Port":"9000","PeerID":"QmTpjKvoXpE6tgWURThYqB3kWzcduq16pbtyb3b2emYf7D","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:550","time":"2019-10-11T17:58:18.526968141Z","message":"[PING] PeerInfo"}
{"level":"info","port":"9000","ip":"54.70.19.206","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/api/service/networkinfo/service.go:260","time":"2019-10-11T17:58:18.7139032Z","message":"PeerInfo Channel Closed"}
{"level":"debug","port":"9000","ip":"54.70.19.206","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:432","time":"2019-10-11T17:58:19.315927892Z","message":"[OnPrepared] Received Prepared message"}
{"level":"info","port":"9000","ip":"54.70.19.206","MsgBlockNum":1028420,"MsgViewID":1028437,"caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:459","time":"2019-10-11T17:58:19.321674666Z","message":"[OnPrepared] Received prepared message"}
{"level":"error","port":"9000","ip":"54.70.19.206","error":"unknown ancestor","inChain":"1028418","MsgBlockNum":"1028420","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/consensus/consensus_v2.go:522","time":"2019-10-11T17:58:19.326380641Z","message":"[OnPrepared] Block header is not verified successfully"}
`

**Comment by LeoHChen** [comment]
the immediate remedy I can think of is to just restart the node program.  However, this seems like a common issue during epoch change.  WE need more deep dive. @chaosma , @rlan35
