### ISSUE TITLE
Create a list of IP for https-wss API endpoints project

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#172]
5 instances/tg/shard * 4 shards * 8 regions = 160 instances

**Comment by LeoHChen** [comment]
why do we need that much?
-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by LeoHChen** [comment]
If we do it per region, 2 would be enough per region.

-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by AndyBoWu** [comment]
it would be more complicated than that - there are 4 shards per regions, and for now, there are 5 or 6 instances registered for each shard per region.

**Comment by LeoHChen** [comment]
no need to have 5 nodes per shard per region, IMHO.
-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by AndyBoWu** [comment]
Okay, I will keep 2 per shard per region then.

**Comment by AndyBoWu** [comment]
DONE
