### ISSUE TITLE
watchdog: foundational nodes and harmony nodes earning rate monitoring

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#179]
We need to replace the current /1h, /4h, /balance page using the watchdog framework.
I think we can create a new page to display the similar content as /1h, /4h, /balance.

Noted, we should support different network, like /testnet/1h, 

Also, we shall support the query of harmony nodes, like /hmy/1h

Those page can be auto-refresh, and shall support export to csv file, as other ppl may rely on it for some monitoring.

We shall also ask for some input from the foundational node community.

**Comment by lawrencegs** [comment]
IMHO, option to get the data in JSON format will be glorious & make it easier for everyone

Maybe a simple `?format=json` ?

**Comment by LeoHChen** [comment]
good suggestion, @lawrencegs
