### ISSUE TITLE
nodes.harmony.one update

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#21]
The content in this page are links to our Google docs, which is not professional.  Those has to be fixed.  Please convert them to markdown format.
https://nodes.harmony.one/foundational-node-playbook/guides

Please work with @john-harmony  to get it done.  Thanks.

**Comment by john-harmony** [comment]
Steps involved
- [ ] Fork the repository and create a branch
- [ ] Convert the google docs to [markdown] either manually or via a [convertor](https://github.com/mangini/gdocs2md)
- [ ] Add the markdown files to the [nodes directory](https://github.com/harmony-one/harmony-ops/tree/master/docs/nodes)
- [ ] Update [summary.md](https://github.com/harmony-one/harmony-ops/blob/master/SUMMARY.md) to include the new markdown files under nodes
- [ ] Push the branch and create a pull request
