### ISSUE TITLE
Watchdog - http panic serving x.x.x.x:64809: interface conversion: interface {} is nil, not main.any

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony-ops#215]
Hi Team,

Please see below, it happened at the refresh of the watchdog page and it never recovers until restart and removal of a specific node ip

2019/11/09 07:47:24 http: panic serving x.x.x.x:64809: interface conversion: interface {} is nil, not main.any
goroutine 248 [running]:
net/http.(*conn).serve.func1(0xc000381c20)
        /home/ec2-user/.gvm/gos/go1.12/src/net/http/server.go:1769 +0xc9
panic(0x8d3280, 0xc00020b8c0)
        /home/ec2-user/.gvm/gos/go1.12/src/runtime/panic.go:522 +0x1b5
main.(*monitor).renderReport(0xc0000e64d0, 0xa0e480, 0xc0001f2380, 0xc0003d3700)
        /home/ec2-user/harmony-ops/monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go:200 +0xa37
net/http.HandlerFunc.ServeHTTP(0xc00008b660, 0xa0e480, 0xc0001f2380, 0xc0003d3700)
        /home/ec2-user/.gvm/gos/go1.12/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xd8b8e0, 0xa0e480, 0xc0001f2380, 0xc0003d3700)
        /home/ec2-user/.gvm/gos/go1.12/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000097790, 0xa0e480, 0xc0001f2380, 0xc0003d3700)
        /home/ec2-user/.gvm/gos/go1.12/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000381c20, 0xa0f900, 0xc000423d00)
        /home/ec2-user/.gvm/gos/go1.12/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
        /home/ec2-user/.gvm/gos/go1.12/src/net/http/server.go:2884 +0x2f4

Regards
Soph

**Comment by sophoah** [comment]
see on discord for the file to replicate the issue

**Comment by janet-harmony** [comment]
Fixed in #216
