### ISSUE TITLE
Nodedb Script Troubleshooting

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#225]
PRIORITY: **high**

one thing I noticed is that the command `./nodedb refresh-node` might have some issue. The command can correctly pick up all our own nodes, but some nodes are not properly identified into each shard such that shard 0 has more than a few hundreds nodes, which apparently does not make any sense.

**Comment by AndyBoWu** [comment]
no ips in shard{1,2,3}lg.txt files.

**Comment by janet-harmony** [comment]
All of the $PSSHDIR/ls/lg/log/[IP] files are empty.

**Comment by janet-harmony** [comment]
Legacy node issue is fixed.
Run `export WHOAMI=HARMONY; export HMY_PROFILE=s3` before running nodedb.sh.

**Comment by janet-harmony** [comment]
IP counts per shard are still wrong.
```
$ wc -l shard?.txt
     183 shard0.txt
     168 shard1.txt
     167 shard2.txt
     169 shard3.txt
     687 total
```

Further debug, errors in the `$PSSHDIR/ls/lg/err/[IP]` for 9 IPs. (These IPs are listed in the shard0.txt file but are nodes in other shards)
Error:
```
$ cat /home/ec2-user/experiment-deploy/pipeline/pssh/ls/tf/err/54.218.17.124
The authenticity of host '54.218.17.124 (54.218.17.124)' can't be established.
ECDSA key fingerprint is SHA256:hKZ5uTkBwKLxr+DEnSaGi6jiBU8ZNl0bjvqNproNdKk.
ECDSA key fingerprint is MD5:04:79:74:01:f2:49:ed:c7:0a:40:d2:d4:2b:19:3e:13.
Are you sure you want to continue connecting (yes/no)?
Host key verification failed.
```
These IPs are not listed in `.ssh/known_hosts`


IP List:
```
18.191.124.168
18.207.138.113
3.0.201.33
3.15.143.214
34.244.239.32
34.250.78.245
52.3.229.56
52.50.161.157
52.53.167.229
54.187.72.80
```
