### ISSUE TITLE
Harmony Node Reboot Recovery

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#23]
We need to automatically recovery harmony node after ec2 instance reboot.

1) add a service script to auto start soldier after boot up.
2) modify userdata script to install the service and run the service the first time
3) after soldier start, run local curl command to re-init, if there is an existing init.json file.

**Comment by AndyBoWu** [comment]
After a discussion with LC, this task will cover two parts:

1. For the running node, we need a script to convert the `harmony` process into a service

2. For the future deployment of new nodes, we need to add a func in the script `userdata-soldier-http.sh` to make sure our `harmony` process will be deployed as a system service

**Comment by LeoHChen** [comment]
I am making changes to the node.sh to let it take blskey passphrase from file input. so that we can automate the restart process.  going longer term, the key management has to be done via KMS or something similar.
