### ISSUE TITLE
Investigation needed for the shrinking disk space issue on the Grafana Server

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#30]
This issue happened before about 2 months ago since when we started to monitor 400+ nodes in our testnet. The issue is about Prometheus service keeps all historical data from every single server, and there is no mechanism yet to recycle those data.

Need to figure out a decent solution to solve this problem.

**Comment by AndyBoWu** [comment]
Available Disk Space on Aug 1, 2019
![Screen Shot 2019-08-01 at 11 06 24 AM](https://user-images.githubusercontent.com/5258417/62332657-49922a80-b475-11e9-9bba-e6bb4581982a.png)

**Comment by AndyBoWu** [comment]
Available Disk Space on Aug 1, 2019

<img width="455" alt="Screen Shot 2019-08-01 at 3 58 23 PM" src="https://user-images.githubusercontent.com/5258417/62332673-5dd62780-b475-11e9-87ee-da49469a0154.png">

**Comment by AndyBoWu** [comment]
Thinking to keep 10 days of historical data maximum for now.


REFERENCE
[1] https://www.robustperception.io/configuring-prometheus-storage-retention

**Comment by LeoHChen** [comment]
use s3 to backup data.

**Comment by AndyBoWu** [comment]
Command-Line Flags: http://grafana.harmony.one:9090/flags

<img width="1271" alt="Screen Shot 2019-08-01 at 5 28 37 PM" src="https://user-images.githubusercontent.com/5258417/62335738-de028a00-b481-11e9-82a6-7d09bb69a464.png">

All these three parameters (storage.tsdb.retention, storage.tsdb.retention.size, storage.tsdb.retention.time,) are unset, i.e., Prometheus automatically keep 15 days of historical data, which is not too bad IMO.

I double-checked the maximum time window of historical data today (Aug 1), and confirmed that the earliest data entry I can find is July 17 on Grafana dashbaord.

**Comment by AndyBoWu** [comment]
lcToday at 5:34 PM
let's keep at least 1 month
 
Andy | HarmonyToday at 5:34 PM
Got you

**Comment by AndyBoWu** [comment]
![Screen Shot 2019-08-01 at 8 08 11 PM](https://user-images.githubusercontent.com/5258417/62341499-7dcb1280-b498-11e9-8fb6-280586664abf.png)

Looks like it is working, but might need to come back to check the historical data later.
