### ISSUE TITLE
Launch testnet (pangaea) network with 3 shards * 250 nodes 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#300]
**REQUIREMENTS**
* short-lived network, it should last for a few hours, and should be terminated every night to save cost
* 250 nodes/shard * 3 shards
* t3.small (or t3.micro?)
* 20 GB (? should be enough for a short-lived network) for the root volume
* documentation to share the knowledge

**Comment by AndyBoWu** [comment]
documentation: https://docs.google.com/document/d/1ykvQpG9NrM5FX94JXdurjFilMhIaoWQAlGA0ShBI_Dc/edit

**Comment by LeoHChen** [comment]
please add the doc to the shard harmony engineering folder. thanks.

**Comment by AndyBoWu** [comment]
shared the doc with engineers.
