### ISSUE TITLE
Tighten security to public RPC endpoints

### ISSUE THREAD

**Issue by harmony-ek** [harmony-one/harmony-ops#306]
Currently, Harmony-operated nodes have the public RPC endpoint port open to the Internet.  Attacker can access this RPC endpoint to obtain sensitive data, or to mount a DoS due to lack of request throttling.

In the short term, we should limit public RPC port only to the regional ELB using the nodes' security group.

**Comment by AndyBoWu** [comment]
CONTEXT
* our nodes are located in two different AWS accounts and a GCP account
* RCP endpoint

**Comment by AndyBoWu** [comment]
@harmony-ek  I assume the traffic for a node's rpc can be from any elb in that region. For now, there are 4 elb in each region, one elb for each shard in the mainnet. LMK your thoughts. Thx.

**Comment by LeoHChen** [comment]
to simplify the 9500 port should only to open to the rpc end points ELB., and to watchdog.

**Comment by AndyBoWu** [comment]
done
