### ISSUE TITLE
Launch more explorer nodes on each shard on mainnet 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#312]
These explorer nodes will be registered and serviced for the https/wss endpoints.

**Comment by LeoHChen** [comment]
setup target group and application load balancer for the end points on the explorer nodes.

**Comment by AndyBoWu** [comment]
https://github.com/harmony-one/harmony-ops/issues/332

**Comment by AndyBoWu** [comment]
https://docs.google.com/document/d/11Y05scCxPwjYsOpdRAFBLo4Cqss5-rNIv7eyeOaRGEQ/edit#heading=h.y527732lhip8
