### ISSUE TITLE
Dashboard Stuck Due to the "BAD BLOCK" error

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#323]
The service stopped on all 3 explorers due to the following errors 

```
{"level":"warn","port":"9000","ip":"34.212.83.111","error":"nonce too low","hash":"0xba3ce493db2a66f46461ca25cdbb6b1126095fec064fdd379180bd1d35b98fe9","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/core/tx_pool.go:662","time":"2020-01-17T04:48:24.53154524Z","message":"Discarding invalid transaction"}

```

I had to manually restart the service, then the dashboard are back.

**Comment by AndyBoWu** [comment]
https://stackoverflow.com/questions/54671543/what-counts-towards-the-500-item-limit-in-firestore-batch-writes

**Comment by AndyBoWu** [comment]
```
{"level":"error","port":"9000","ip":"13.57.202.90","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1667","time":"2020-01-18T02:17:49.022166662Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 3 EIP155: 0 CrossTx: 0 CrossLink: 10000000}\n\nNumber: 9651\nHash: 0x7393e4960822ea63ac707a81ac8fb8581633065922dbc1e120687e8669e67b91\n\n\nError: unknown ancestor\n##############################\n"}
{"level":"error","port":"9000","ip":"13.57.202.90","error":"unknown ancestor","blockNum":9651,"parentHash":"0x179751a03af2ebb5d12955454928bdc808c72e3f0417f2a244574f0cf934bf8e","hash":"0x7393e4960822ea63ac707a81ac8fb8581633065922dbc1e120687e8669e67b91","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:445","time":"2020-01-18T02:17:49.022196542Z","message":"Error Adding new block to blockchain"}
{"level":"error","port":"9000","ip":"13.57.202.90","error":"unknown ancestor","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_explorer.go:129","time":"2020-01-18T02:17:49.022202425Z","message":"[Explorer] Error when adding new block for explorer node"}
```

**Comment by AndyBoWu** [comment]
Latest updates:
* e0 and e2 are up and syncing with the network, but not to e1.
* harmony.service is online on e1
* I fetched some new error logs, and updated the ticket
* s1 is working fine, consensus reached

**Comment by AndyBoWu** [comment]
{"level":"error","port":"9000","ip":"54.153.35.103","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/core/blockchain.go:1667","time":"2020-01-18T22:12:26.463931587Z","message":"\n########## BAD BLOCK #########\nChain config: {ChainID: 3 EIP155: 0 CrossTx: 0 CrossLink: 10000000}\n\nNumber: 18406\nHash: 0x0d92b74ff159664f2bacb72c5e4bab0a7bd4dbbe0d39120327d1f17758127627\n\n\nError: unknown ancestor\n##############################\n"}
{"level":"error","port":"9000","ip":"54.153.35.103","error":"unknown ancestor","blockNum":18406,"parentHash":"0xf860362daeb2e41397a136fe401d27653bcdeb9843441ccf8aade17f90b28e2f","hash":"0x0d92b74ff159664f2bacb72c5e4bab0a7bd4dbbe0d39120327d1f17758127627","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_handler.go:445","time":"2020-01-18T22:12:26.463956762Z","message":"Error Adding new block to blockchain"}
{"level":"error","port":"9000","ip":"54.153.35.103","error":"unknown ancestor","caller":"/home/ec2-user/go/src/github.com/harmony-one/harmony/node/node_explorer.go:129","time":"2020-01-18T22:12:26.463961618Z","message":"[Explorer] Error when adding new block for explorer node"}

**Comment by rlan35** [comment]
@AndyBoWu Discarding invalid transaction is expected. It's a error log for invalid txns, it won't have much to do with the node failure.

Again, unknown ancestor is a side effect of failing to fully sync up. Please make sure the sync nodes under dns are working fine.
