### ISSUE TITLE
/1h not able to access leader information if it is a gcp node

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#334]
![Screen Shot 2020-01-20 at 4 31 05 PM](https://user-images.githubusercontent.com/5258417/72765650-4cf3ac80-3ba2-11ea-9b6e-db7039feabd0.png)

**Comment by LeoHChen** [comment]
/1h is using hmycli, why GCP matters here?

**Comment by AndyBoWu** [comment]
INVALID, just updated leader IP for /1h webpage.
