### ISSUE TITLE
Scale Down Current Legacy Nodes from m5a.large to t3.small 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#345]
* This can be dynamically converted based on my understanding
* t3.small **OD**

**Comment by LeoHChen** [comment]
we kept around 10 legacy nodes per shard for DNS setup and RPC end points. Be careful.

**Comment by AndyBoWu** [comment]
Any chance to lower their instance type if t3.samll is not powerful enough?
