### ISSUE TITLE
Terminate `explorer2.harmony.one` 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#346]
As it has fulfilled its request for token swapping project.

**Comment by LeoHChen** [comment]
really?  I thought we want to keep for a long running explorer so that we can test new features on explorer.

**Comment by AndyBoWu** [comment]
Yep, got confirmation from Sahil. 

To clarify, I `stopped` the instance just in case we need to re-use it in the near future.
