### ISSUE TITLE
OpenStaking Network Lost Consensus 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#354]
Watchdog: http://watchdog.hmny.io/report-staking

We created a network with 3 shards, and 8 nodes for each shard. All three shards lost consensus around blockheight 250. The version is deployed from the master branch. One possible reason is that the shard lost its consensus after an epoch change.

**Comment by AndyBoWu** [comment]
on leader of shard 0

```
{"level":"debug","port":"9000","ip":"3.80.198.253","myEpoch":3,"myBlock":225,"myViewID":225,"phase":1,"mode":"ViewChanging","error":"Validator 2e9aa982036860eccb0880702c5d71665761f8d4e6ab5f3d8c3aee25b3e68a2c7eaa3cd85972c7f9a3c19d3fed3d5d01 is not in committee","caller":"/home/ec2-user/harmony/consensus/view_change.go:166","time":"2020-01-28T15:58:04.12781647Z","message":"[onViewChange] VerifySenderKey Failed"}
```

**Comment by fxfactorial** [comment]
that error is misleading, I've been taking them off some others errors

**Comment by AndyBoWu** [comment]
> that error is misleading, I've been taking them off some others errors

the error may not be relevant. this is the latest error on the latest log file.

**Comment by AndyBoWu** [comment]
@fxfactorial s3://harmony-benchmark/logs/2020/01/28/074735

**Comment by AndyBoWu** [comment]
updates:

relaunched the network this afternoon. shard 1 and 2 once again lost its consensus around block 255. Even I rm'ed .dht* folder, and restart the shard, these two shards still have trouble to reach consensus.

`[ec2-user@ip-172-31-37-52 pipeline]$ ./run_on_shard.sh -T 1 'tac ../tmp_log/*/zerolog*.log | grep -m 1 HOORAY'
run_on_shard.sh: using timestamp 20200204.200947 (from logs/os -> /home/ec2-user/experiment-deploy/pipeline/logs/20200204.200947)
run_on_shard.sh: using outdir logs/os/run_on_shard/2020-02-04T23:14:45Z.UZArMV
{"level":"info","port":"9000","ip":"52.87.165.0","myEpoch":3,"myBlock":225,"myViewID":225,"phase":0,"mode":"Normal","blockNum":224,"epochNum":2,"ViewId":224,"blockHash":"0x8812e3956108f3b1310ca373b372ab3a233699750011fd23d4311de2641c43df","index":0,"numTxns":0,"numStakingTxns":0,"caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:874","time":"2020-02-04T20:45:32.165359099Z","message":"HOORAY!!!!!!! CONSENSUS REACHED!!!!!!!"}`

`[ec2-user@ip-172-31-37-52 pipeline]$ ./run_on_shard.sh -T 2 'tac ../tmp_log/*/zerolog*.log | grep -m 1 HOORAY'
run_on_shard.sh: using timestamp 20200204.200947 (from logs/os -> /home/ec2-user/experiment-deploy/pipeline/logs/20200204.200947)
run_on_shard.sh: using outdir logs/os/run_on_shard/2020-02-04T23:15:05Z.WtkIuK
{"level":"info","port":"9000","ip":"54.90.29.44","myEpoch":3,"myBlock":225,"myViewID":225,"phase":0,"mode":"Normal","blockNum":224,"epochNum":2,"ViewId":224,"blockHash":"0xd33173ab80874a1a0e8b704a794102f003524acbee28bfb292b7c7460a8dda2e","index":0,"numTxns":0,"numStakingTxns":0,"caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:874","time":"2020-02-04T20:45:36.47707871Z","message":"HOORAY!!!!!!! CONSENSUS REACHED!!!!!!!"}`

**Comment by rlan35** [comment]
The testnet config is wrong. It used pangaea staking epoch for epoch transition, which doesn't align with the real staking epoch transition, causing insufficient votes at the second epoch transition to 3 nodes. this will fix it https://github.com/harmony-one/harmony/pull/2182
