### ISSUE TITLE
Enable Travis CI to VDF Repo

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#36]

**Comment by LeoHChen** [comment]
I just run "go test -v" in vdf/src/test repo on my mac.  It took more than 10 minutes and not finished.  So, for now, I think it may not work in travis.  @coolcottontail is there a smaller set of test case we can use as the automated CI test cases.

**Comment by coolcottontail** [comment]
hi Andy, please use these three for TravisCI
https://github.com/harmony-one/vdf/blob/master/src/test/discriminant_test.go
https://github.com/harmony-one/vdf/blob/master/src/test/fast_vdf_test.go
https://github.com/harmony-one/vdf/blob/master/src/test/classgroup_test.go

**Comment by LeoHChen** [comment]
just run ```go test -v src/test/discriminat_test.go```, and so on
