### ISSUE TITLE
e1 unable to join the MKTN 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#361]
Looks like e1 is not able to join the network, even I tried to
* restart the exp node
* restart the entire shard
* reset the min_peers to 4

error log:
`
{"level":"error","port":"9000","ip":"174.129.166.23","msgBlock":1743,"caller":"/home/leochen/go/src/github.com/harmony-one/harmony/node/node_explorer.go:66","time":"2020-02-07T00:18:49.222798214Z","message":"[Explorer] Failed to verify the multi signature for commit phase"}
`

**Comment by mikedoan** [comment]
what's e1?

**Comment by AndyBoWu** [comment]
explorer 1 of the MKTN, do you wanna take a look?

**Comment by gupadhyaya** [comment]
fixed in https://github.com/harmony-one/harmony/pull/2181
