### ISSUE TITLE
Shard 0 in OpenStaking Network Out of Consensus

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#367]
`
{"level":"info","port":"9000","ip":"3.83.154.61","myEpoch":631,"myBlock":47399,"myViewID":47399,"phase":0,"mode":"Normal","blockNum":47398,"epochNum":631,"ViewId":47398,"blockHash":"0x4f6ea923325c875eeb8dbc299a7024c3c7849a2dc094b281d45c61d0b7ecf255","index":0,"numTxns":0,"numStakingTxns":0,"caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:874","time":"2020-02-10T14:41:11.77966374Z","message":"HOORAY!!!!!!! CONSENSUS REACHED!!!!!!!"}
`

This is the last consensus msg we have for shard 0.

**Comment by AndyBoWu** [comment]
1/ service is still running on the previous leader 3.83.154.61

**Comment by rlan35** [comment]
harmony is running, pid=19288
panic: runtime error: index out of range [1] with length 1

goroutine 506 [running]:
github.com/harmony-one/harmony/consensus/votepower.AggregateRosters(0xc00e8f5d70, 0x3, 0x3, 0xc00e8f5e90)
	/home/ec2-user/harmony/consensus/votepower/roster.go:96 +0x771
github.com/harmony-one/harmony/core.(*BlockChain).UpdateValidatorVotingPower(0xc0002ee000, 0xc00c35dce0, 0x1500, 0xc00c35dce0)
	/home/ec2-user/harmony/core/blockchain.go:2535 +0x19d
github.com/harmony-one/harmony/core.(*BlockChain).WriteBlockWithState(0xc0002ee000, 0xc009c940c0, 0xc00dae3280, 0xa, 0x10, 0x0, 0x0, 0x0, 0xc00d5713a0, 0xc00b6480d0, ...)
	/home/ec2-user/harmony/core/blockchain.go:1220 +0x1959
github.com/harmony-one/harmony/core.(*BlockChain).insertChain(0xc0002ee000, 0xc00b76a9c8, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ec2-user/harmony/core/blockchain.go:1488 +0x1243
github.com/harmony-one/harmony/core.(*BlockChain).InsertChain(0xc0002ee000, 0xc00b76a9c8, 0x1, 0x1, 0x1f7c101, 0xc0103d7980, 0x3, 0xc00b76a958)
	/home/ec2-user/harmony/core/blockchain.go:1308 +0x73
github.com/harmony-one/harmony/node.(*Node).PostConsensusProcessing(0xc000184a80, 0xc009c940c0, 0xc00776d180, 0x63, 0x63)
	/home/ec2-user/harmony/node/node_handler.go:375 +0x91
github.com/harmony-one/harmony/consensus.(*Consensus).tryCatchup(0xc00036ec80)
	/home/ec2-user/harmony/consensus/consensus_v2.go:1064 +0x4d6
github.com/harmony-one/harmony/consensus.(*Consensus).finalizeCommits(0xc00036ec80)
	/home/ec2-user/harmony/consensus/consensus_v2.go:825 +0x31e
github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1.2(0xc00036ec80, 0xb927)
	/home/ec2-user/harmony/consensus/consensus_v2.go:1272 +0x9a
github.com/harmony-one/harmony/consensus.(*Consensus).Start.func1(0xc00036ec80, 0xc000087bc0, 0xc000b607e0, 0xc000086cc0, 0xc000b60780)
	/home/ec2-user/harmony/consensus/consensus_v2.go:1274 +0x4dc
created by github.com/harmony-one/harmony/consensus.(*Consensus).Start
	/home/ec2-user/harmony/consensus/consensus_v2.go:1100 +0x67

**Comment by rlan35** [comment]
New issue after restart, validator can't verify the blocks anymore. Seems data corruption issue:

{"level":"error","port":"9000","ip":"3.83.178.66","myEpoch":631,"myBlock":47399,"myViewID":47399,"phase":1,"mode":"Normal","error":"[VerifyNewBlock] Cannot Verify New Block!!!: invalid merkle root (remote: 7b64970a829d6c74fd718db598879b19106a2b1f0ca35b96413f7192681eea91 local: a4e1a3795bf27f0c04ccfa70d8766ede731290cdabf095dc71a050a893d28bf1, rlp dump f91f6687486d6e79546764827633f91f58a04f6ea923325c875eeb8dbc299a7024c3c7849a2dc094b281d45c61d0b7ecf255943f6e680ec5456f540a833e77df4c8ed20a20f274a07b64970a829d6c74fd718db598879b19106a2b1f0ca35b96413f7192681eea91a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000082b9278404c4b40080845e41bb9980a0000000000000000000000000000000000000000000000000000000000000000082b92782027780b860ec8bcb17b324eab3577ca8219f54e7db8f23bbb684eca92aee25936df32c12a2ed3a8d9923612aa19eee3db9997ec40e472d6fbb82daa24ff831270219331657e40fbce35ff9360fd660dd5bcf774ce55a0d53f6244479e0e0cfa846a0c51782837f00088080b913d1f913ce820278f913c8f9069580f90691f84794261fa45c6a09cd3faa277d829e91d9473973357cb0e7f54994bc5c02edeeb178ce2d34db276a893bab5c59ac3d7eb9f077c893f9e31171de6236ba0e21be415d8631e45b91c0f847946488ee7067c59adde2ad810da03509a15f9e3fddb0b7aec767534872af7c905da7318cddf2248b0834ec1d64944ad725878cca0833f14cd3b2f7f01b6f041d573fe67ec299c0f8479413f8d143f73866f3a8334dd0591b59b3a19d9cecb09f5f8c5dbe12d14ae8468828754c4db3f2129c69de88baee4e361e38000aed54da204591bbcdeeeb571ffff81e9ade02c0f84794d8c23ff826e00220bfa7ab6966a85998574f1c63b02e9aa982036860eccb0880702c5d71665761f8d4e6ab5f3d8c3aee25b3e68a2c7eaa3cd85972c7f9a3c19d3fed3d5d01c0f847944092ac6d9a7f87aacd7787b5c1c4541d9bf2cd5cb01833721b78797a16b1987734d05b08b9444e24075fda50ff2acc7b8a6d8e0aef0829bcb11e3b9df7466cf8a39e4e4101c0f8479461ef891b705e7f0a81ea499beec0f280bbf2af45b015e5b5b1b455d8814d8986f9fd00bd64e897506c8e958bbbfd6f43e2302837ab625096f19f05b751fceac5caf387f483c0f84794db8756abae760de4aa71c15ff2597a1ea12657a8b01bf1ca37df49190578391d3c34cdb62cc9b2c88ebf5bbbe72a41db8da5236576fdb4513973045f23633a6ddd5a52488ac0f8589400213546f93e3f68c420388f497a440036e8742eb0efad224a05fa7497f99878705c45ff0d13ae94eab209804c22f02ba1d66b5d8d6636faea0dbba0069637445830111b99d1900785ee10d5da46d900f436a000000000f858940033a3074812ba9ede87b64f6f75b8acf0b889eab0b2f52c611c74fbf223b3168d6e89d4bf51c0a6c58a02d3158b4f146e96c51ff324056dc480b89a9a5dc8ee87bf915989d1900785ee10d5da46d900f436a000000000f858940077c61035ce1836d0156b8b5a6fe42299383e25b0c88a472722e24a71d7646b32c95c0f14daa49f901a4e6cf9a34e43850a67c060745ba481c1b39c48b745c62a8227ef83d1900785ee10d5da46d900f436a000000000f8589400b0f6a683a4ba5edc9c5e5a8c0b5ba65be8b788b0287db3b1cbe5c8f8103763bb5fd2a80648db0082aca11d6afb0aba803331e7d1129b28b6498760ffad45f374c6230010d1900785ee10d5da46d900f436a000000000f8589400b1ce62598f1a365e302b5d63c53b79040c087db0815aab5dcb59b038a29d8641adcc04d56d8e62fcfdbef6732ca633c27c27856277c225bc1e84d28160dd851bf3321408d1900785ee10d5da46d900f436a000000000f8589400cff196c0bb1c7d68679d3ab03a9320184b5473b04c9563100575efedbe19a938bedf50b2678d5b406c33dcbc1ee2012fec11f35b31c4eed59653b36cd4a6198bbcfbba98d1900785ee10d5da46d900f436a000000000f8589400f9314a95c2ed0518de1c8f7b71ef5e55006131b0bd9b6199caff9166c582b328c1d5897c2febc81e96b4afbc9b750f9334df3d07f07b51c5f7c72247a2632ed86cb28206d1900785ee10d5da46d900f436a000000000f85894015410b9ee87c8ca65a2afda6c6832227176d55fb0f5a1c92ecbae66bf573740e2d57643c9411fd01d79844000a43e9d1c8b744ec4f067171a275eebfcfba4926e6c675004d1900785ee10d5da46d900f436a000000000f8589401614ebdde2fdfa5151c940a87befbb6119a4fddb0eda157218e3bae885b8223a91bb4c80d078d1cd0a758f9f9e83e1c81f3caa673a5c594c83f1e45d2eebb375581ecb098d1900785ee10d5da46d900f436a000000000f8589401682480246daaf8bbdc2989076e4c53cb41441bb0b00a6eaa483d22200906efd6aee2bdf7b54f2a6bc3ee72bde53e0db4d22907c2f4f80d8009e5fac30578c1e86069490bd1900785ee10d5da46d900f436a000000000f85894b6fc641f3134890f74412a6a609ef6778acdaaf1b095b7f81b4ad71a93e866c918a122a8754cf6db02c0f3df93d00e6651b77323d527ac39fc3e990f9c2f6e1e3ea9d15112d19008a6d1c68f87d1798de5a53800000000f8589496d4c71cb2b0b370c411a4739f1666583ed63dddb0aac23a57ea740120f3b790a00574d1083e09a57de16c7e8b0232a4389a658f7922a8f123d3c65fdbc954d9b54667310dd19008a6d1c68f87d1798de5a53800000000f8589444a06de5c2740bb5c533d525b6dc71cd6f9f94c2b0a689b39bb1de4f1591e29094b91d00596b0f371ea16fadf8b4143c680a1f9aff3e805e167eda2c583827ed0e7c8c9882d19008a6d1c68f87d1798de5a53800000000f9052d01f90529f8479475ea17db98f7266c89423a4ea12677822ab269bcb04bf54264c1bfa68ca201f756e882f49e1e8aaa5ddf42deaf4690bc3977497e245af40f3ad4003d7a6121614f13033b0bc0f847940f25138bbbbff872e662c364ed0ff7f81640ab1ab099d0835797ca0683fb7b1d14a882879652ddcdcfe0d52385ffddf8012ee804d92e5c05a56c9d7fc663678e36a158a28cc0f84794dee622a09ce7602a28bbdac588ab10f302ceb5afb03434351415d20b3b4a5014b9aca44703dfef332e50e008a59ca8d1f9bb41b0ea695fb74a0f9e346138a429d08c24c793c0f847948f01d364ee1aa51e8a5e8116ca179d7a53152bbcb0b9486167ab9087ab818dc4ce026edb5bf216863364c32e42df2af03c5ced1ad181e7d12f0e6dd5307a73b62247608611c0f8479406992099a65399d243b791b6f0596f8f00731248b06ed606f323da02b0e18d64a87a1b42641d847c15e9e11596e77d87d34f26679785fb4e76d270dc9d14bb539f02157501c0f8479450be91354b22668c22f0f8f6ca78db9fb38ae018b08c95e04a4826d4d80ef16183f13aa5d14eb3c96d2755407e15c440bb4edd6e4636a82e47975385c6223ba24759561103c0f84794f46d8d2c403ee5d48642de6bca8db74c4338c8f8b0c2f66a6948be4f2747f5938091898357f96839a8a6766c1be80f989fd1e85fb7eb9b744aad6d6597445bc09d5ef7a916c0f85894006d3e73347410f5f3830e613ce217950a3d1b7ab0b3330b2ebc30a470c7ead165585c6d242933699174d68f710ad0137237ccc3175d44953151bf666b59f618dc5c357492d1900785ee10d5da46d900f436a000000000f8589400acc91c3c39fde7f8f250b02ae449e4cfe60fc5b0f5a023a8ed2e8f8741b001b9e108211e61a13cd51c49be580c275a7b72a42606038ba44673b50c94e8868aeb3b10da92d1900785ee10d5da46d900f436a000000000f858940110f22d73c73d0a9930f018e4992c083e95dcf5b02646c30a75618a330b1125f9521689e1932299e79147aab857f7cf516f99778f7c33723a5bc6339488daefcc96f6b189d1900785ee10d5da46d900f436a000000000f85894015fbfc048f5cdcdbde61c424ff55b1481936a70b09cd78588bef7a9f4edb0c49fc2709503ecccab08d0914851c41c4b40bdd8fd67d0bc81cf46cf3eba0c4edda8c2983d0cd1900785ee10d5da46d900f436a000000000f85894f3cc08245ba99bbe13a6a55740b161a7e845eb5cb07cbec49a516f7e4901a7fdae5ab16fc8e6cb4e3a3a7dd2e847d865b1241171ccbb2069fc523f2e56749efcca6bfad503d19008a6d1c68f87d1798de5a53800000000f85894ff794c3b613ae1460df37c746f2eecc88f12c934b0dca067f9048310f50d0fc90aa499aff917a4ec4a75cffaf814eb4242fc93c3bd52acd73af8bf6b42a57f36bf91bd3e04d19008a6d1c68f87d1798de5a53800000000f85894e6b157646a6db7ed7afb967379bb9a5801c1e948b07a43b05c6a2d9ba06bafdc22c4ef48a0e414775ab5b73de3fa34f8537260e8e82a70676326f2b4e8e9af086de36f1018d19008a6d1c68f87d1798de5a53800000000f85894e6b157646a6db7ed7afb967379bb9a5801c1e948b00fa65f1e1ceed2da9aa2d0a63a6392bc4fee15ca0488ddf804fdbf5bf3c40de195adacb76a4a8d15a97ce762cd67be93d19008a6d1c68f87d1798de5a53800000000f858940cb90cc9d289b88f157d446923106cfd45279b7db0eaf562a9c405df5500ff6f967dcfc8ad5ed8e3e1a879dd056f7b77b365b2027e0aacd5fb6be13dcc20f756d3863dcc18d19008a6d1c68f87d1798de5a53800000000f907fd02f907f9f8479485c5691d6b229dc545ee84b1ef84a6059d7c5d59b0e212c4c5cd8e078aedd34c300ae500c5bd5fd036231d1c9dcc8400337919a59ebd47523faa209fc0d873ead492621f88c0f8479436b79e51601704f69219970ef135585257cdcf6fb0f441b75470919983ba18a0525b1c101af42cae052c6d50f74d1553eebbe78ef226849c5e5a7fb2ba563eec6b20380c00c0f8479468771f0430433219248c8777d82a9b6a8efc2d1bb08a211eb5e9334341fd2498fb5d6b922b4a0984d6a4ea0b5631c1904de5fe21fd6889c9c032d862546ca50a5c41294b0cc0f8479489034ae4b624c4ea791551fc765d63171574ba33b088b4da322731de51da65e6d2faba85782fa517002f6177c19932c10767cc6cef922ee17f7e46ff00424b8ffe4afeb291c0f84794fd5a1ada043d122c5fe3a050d0d1d97fc383b604b0bb058f47d3d66e21d67d7a0b0ab0dcd87e037e590ce47ae9470afef8f682a5ac79fcf3f79b89ecb0769cc1ae62ac9290c0f847945786636bef546a4a5b276f529432434f6223609db0021926136495a0adcdda5af0602cb4b4ce6d6529cfd451b844728a0e4e424f2a78879a8b5d5e4b3e42127f95f2e2858bc0f84794234f723b141dfb0d47eadccbda96e838a699dfaab0a2b1b534c94bf19a92551f1d32d62b802be6996458f65b0baeb081c9972b34d72310e675fc7797b9c860d8cc223cee8fc0f85894002c991de605d488be82e3864000c9835e0042d3b0b6791d46482a76ccb4a5adae779aa2afda56725ac50c06ad5e7a777e91cfedf326c70b8b00e97606477b2b4f279f4981d1900785ee10d5da46d900f436a000000000f8589400432d3617134e8d33b812ef7dce4061364576cfb064234cf9b0c48936960691dfc96ae827c4c1cc12f1108c5c91450b19b2e2b30b719b11e2901b9e508b098b3b873eaf85d1900785ee10d5da46d900f436a000000000f8589400460f316b1620b315196962a9fa8c527afcc8d9b0eb44b6fb9342cb9054d2ee8606a86e793bf033b09b2c8e3f99fccae784a6a455f32e2d9699d244795e81a25a5fc5ee95d1900785ee10d5da46d900f436a000000000f85894006c6853533f7e40a2c938d2ec44b3a16313f5e8b00bfad8471d8f7c1bff6675191b61e10adec7caf0bdd34c21bb0354820123c37c65886c689256f4c5df07d062bd627f85d1900785ee10d5da46d900f436a000000000f8589400b39e610c089aa1b1f54251be599e15f48d946bb0065d9e659a9a1df10b38a4688afa7271822d88ac547c5359e6c3ee74bb6b0bca5b22a005cced713ecf0ddb682ca9a58fd1900785ee10d5da46d900f436a000000000f8589400b900a2122f2b014989c20a496d33138cf17b49b06acf5c33b70208d25296c5bcb9ccb37263cfe273e08164c2bcaffaa51463e1cff19807f63ffa7ff3ececa7fd25bbfd80d1900785ee10d5da46d900f436a000000000f8589400f0932d6082b2213e66b5481a355d38d10929e0b0752a87820fd614150214ef0dfd116f91f7bdc7c7979f9c33d5c86f8712430d71679c1cac49221c45eeff6e447de70108d1900785ee10d5da46d900f436a000000000f858940151fcd00313e97e8b5ac89875b0849630fee12eb0037850c3b14878ac4280a8bb820113548039ac00178ae47c3ff0b3a4cc3f37de688d0c92a0a624b2c1fc54c684256d02d1900785ee10d5da46d900f436a000000000f858940169d7cbdb7b33481eef6424b7a6b89b9c264bd9b001528849670f3daaf9c020a1456bf7ad65154995aacab0aae0f78ba224ad3b455b050ff9569df2cc397f3f7a1f6ec515d1900785ee10d5da46d900f436a000000000f858948b3d640598a263a2111fe0c62628a397dc548c01b02506c7d1eed7b61f483dedf6800d7a69603871a172ee1a1e6d202e77fec5564261d7a5117a82e6a9f5d6f0d26c8b7d02d19008a6d1c68f87d1798de5a53800000000f85894c16f1e795814350b7a945c890cf8d45f9fb89c21b025ba99368cce424fbe14d75ad664ad3690c09bf3d613e9f1073641ee286ff8bb583d579c41764e93fb6c3cc201029506d19008a6d1c68f87d1798de5a53800000000f8589409cb74bc58a16b2c5a515b85abb4d35dd4cfdec9b09cea579bf599442be9fdb5441f25161d17b598455a68982f85a6a27f05f652b57ccd84e815ac0fcfb45e5e15ead98b15d19008a6d1c68f87d1798de5a53800000000f858943ea787861fea3240637cc8cc46cee862d46a011ab0cfdb691354934308dd8cc565c7db066aa75ff395beef97658e12e25be9b53638e0274d5d53c50b43e37c1bf8d327a70cd19008a6d1c68f87d1798de5a53800000000f85894ede451dbe302eaf4fb0b4cd2998e473d4de14432b0415ab78653ca61c1f0ba48b3ec385f1989a45666e0a3bc9562350cedf1be6787ad09c5b6126d9fa670c4c9dc26782c0cd19008a6d1c68f87d1798de5a53800000000f85894879217c87b697d982dc4cc777b07c68013553274b0e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116d19008a6d1c68f87d1798de5a53800000000f8589461e24e310d10e45320da2f1c0decc2b869340f02b0375b66371991246bcd27737d4ab85e74cd3c39c888278c4eefd0fcafa6a80fa3ae956a1107fa95f666a549322d93a695d19008a6d1c68f87d1798de5a53800000000f85894a71dce2ace5dfd431a0114fc3acbaac4eeb0a016b0f7c2a681bbcdceab18d575fbdd25ff6e6cba4f416f2cf0c07ed4254cfe28dc433f7a308eb8bfb27bb2cb2404aa601d18d19008a6d1c68f87d1798de5a53800000000b90903f90900f88da099fb87142970d9101db36de3a41335217e13ef3778f2cdfdcb77768ab6d2e56982c4aab86014ec2295af3ebf7fe552a401c507178f8cd99a14c2594877cf545fda469653dca3400b9259d00ef757a073fc13689f184881fc83c878f04188e599db404e6850212615ed605e563ba7f8e4ea16fd3c6cba9f0e1f5ed999e38b73f02851f0bd02827f6001820277f88da09b07c5d51df82b78566f5cb89b33ec85485231c792c9a39a0120008bf07deef582c4abb860c9e46af5ec64b78bdc30d18618bcee0680b967ed43da470d56f3b58473e2e11f16a7f40be5064a29b2d2f307989ac8003b1b83cabb2de242c5b36b756043b19e522181504eaada8160a2a05b849de96dafb603dc1a6d76f3c5099c9043ab708e827f6001820277f88da0d94f22fa32f8054812214de6e01dd8b44b716c89c7361b8ff771c84d6afa946582c4acb860459705076be3aaeda535f150dd126b59a4c2bfe81e80874a61d361fe788658d854d7880ca21c210c042391a59f853a06a3aeffe6988eb696000bdb6eef00c45ff663d2fb1c413810374d21940a8300279eb43394acfa0dd7e65ebe30c386fa0e827f6001820277f88da09440699305b06fa7bdb615680408eded6817fe7f0e78127ca7856ae6c3ae1d2382c4adb86083d0886d1154bf3ee572700340425d35c063286386424d0a52464e5890000012c01d267ebd3ffc2a9b2bc9900d43260673c06bd3d015c414cd6a8714bc7d5093471a7912552361ef088c0330c925ae175a73b65d569a9f1ad406b0f20272ca13827f6001820277f88da01b07a18e448b4af5df18cc9010ca23d42caa4621c0b46808a640558c040de4aa82c4aeb860d8d0eb571d771936c7605e9ad43e964b51e8931f2756cec227002d4a8fd9bf56544f4c8e87d1a40232756e345c16201779847eaa5422e725d9f32819b96b7a48c52943fed3b648957f62ecd0d845f781992397f9a458acbbdf3aee052a8a3397827f6001820277f88da06de71ae3a8c2c024dea42ae3bd8da6259c3fd381139d8430c8b0b63e3c639a3482c4afb86077377caeb1ac7a70df8c0b2580a9b93994ba2cc33d5f26a1be1498b12c25b6ea7d45bd5136467064cce57dcedb4b9a14b5ff33cae397cc7751e221cfdc480891c5b13fe187a9aeec28c2093fa9c6801a7b78895a665fad3e8196ce8a62f0cd0b827f6001820277f88da005e2e254125f0330753f5e94ba9c0d4bf5d3534f026ac63306dd1772b4e1bc2d82c4b0b8604769d0e6615174b978b71653e69df002d9e9844efab911c9751aece5beef8e8d7a8b900af574630bce492c142bbf6c08b8c6a97c73ad5cdbebc6792db8e97a2891cbeeb06a3c301c11087c52f42cb41d94e2237aba284ba3545dc8e2eccf9518827f6001820277f88da04e17fcf35a3109a65c89243017d953618da5e8b8397322ca49733f2a0c28e33282c4b1b860087dd8fec51e1a57cf2076cd205408c3478db8bd2496d91c0030d3daddf2cca9e687582c713b39cfea8b1230ce111109ac9690dcc5a7af604d18466902b8c08fc516df0ea7242026813f1ad2f09d25c89f53d78cf19154b27e0b9e15a2de0702827f6001820277f88fa016020980a1e6094c6db44fd5fe65304f1d52ebbd8a5efec7d7f9fbb8bb8b39be82c430b860d0ce56e13f1fb18f2b2e19563144c3406cc835ed8ab10cef186ec89c9371dc1a3778c8f59cad786520c9d0c41c93550d70fe37c562cf7c84b2f3a4cb46bf1c04e6542a5ccc9268586b0515b6dd24051a4ad52caa895ff3d6690fb655a87e2d85847f00440002820277f88fa026c451e9e8d256ca640283756e0bd2930c266e9694ae33bb0eed8b41d6e26bad82c431b860c5f8147a0e3e1a1d8d19005ed6793b6b97b7f84de429838aa76fa51c17d3313fba32824f58d3fe157b52f4e8b28a9214538e250e463cadf6926c35862ebd254e55f095a50a5ec96b70a259c179cb066cc70d726e4133d92b87b2696b40773287847f00440002820277f88fa04acb3ddc666951eda3035de3f4724721bee3acf509850ada15e131df3842b8c782c432b86025591ec2f75d8704fa9bebdb0f86d1d9a363a46f4c4daeb5a99ec00ac5b4fe57d03d76323bb037dbf09b61a8158e230497a35521551ac74b60560656515312180f6bd7cefa5d83d13e7ff6ff219c4827613513d30c5ca29681b47717b8a0f191847f00440002820277f88fa066b3edd90db76a2cc143aebc037d7bd1b6aa602a66537363c2e95bc078b0a46d82c433b860e113d617b5416a041efbfc77a3c027251f5691579ea069a34ed0fc65dc3c46931b25053e4b771dd2fc2a8b7bac6c840c2a0153447adce9f3994484d387e9452cebd885fc952afbf36ef3c3260e582c8d701ebd6281511088456d6ac3ecedb719847f00440002820277f88fa0c7f7b5283da4f52ba3f2d65efd93445ccc2dd7fa59b4c46aa4e973fd09b388dd82c434b8602df6c726a6a6c2bdfa6ca2d797fc7515ef0854922657066f7b136a8142a4b25e28ceb3157e972317693cbd3ab8e2710b9f488a1e5a3ba911326e5826fbdb5aa7c725af2ffb4ab661bd7f03b3f9bc2fc04eb34583b522eccd2f8fe10ba264ec97847f00440002820277f88fa02d96461b15a37fae57e74e2106a77e4cd0419ceb576bb3e6d219de3fec5598dd82c435b860283435236e5cd4988d94da86d59ccf60c836aaeab041a58dbcebae4a4b65d9f33eea73120e11a77e387a5b9e0670d50181f30888ba5a1b3c8e79c21ab206cf26a9506d2ee89e76952a3fb53af2d8393bd918da0ebf526ba08c23a408baa36691847f00440002820277f88fa0fe4024ac412b9d6d99033cb54f441c491377cafc1ff7734f3c8b98cec7e273ca82c436b86065bf83e582a492658bddf5eaf603cd08875a3341429fa04b3e25b9d43051d918242e179d5e8ef568ee3d08e11da74510ee8a03ac38826afed95970e520f7b5c51906367fe4ab00f0ab6228ba8387949804a37dc71bdc71e5d2bf6ec1444a3607847f00440002820277f88fa0b84f1f355f63b7f09a14cf6a39297507ebb5b737ed839cc280ac740ffd32bb9682c437b86065bce5465f42a6d636ecfdbab74228f2c68d826d543ef2a8979b8e45a966001b3700cb6d3430fc21df2405db9d4d4417af9479fbee33d25afdc16a0272349b09aab17a28260d94f8eb30ce47a822ce26634c325b133e85aca5d2ce0a54044a06847f0044000282027780), numTx=0, blockHash=[5 68 217 23 99 198 161 45 95 166 24 177 131 198 142 235 35 251 143 23 135 21 58 184 27 205 88 186 147 225 124 207]","caller":"/home/ec2-user/harmony/consensus/checks.go:163","time":"2020-02-10T20:23:51.34685719Z","message":"[OnPrepared] Block verification failed"}

**Comment by AndyBoWu** [comment]
@rlan35 @fxfactorial 
logs for the current network: s3://harmony-benchmark/logs/2020/02/05/194344

I am going to wipe off all the DB and restart the network.

**Comment by fxfactorial** [comment]
appears fixed
