### ISSUE TITLE
Provide intended shardID in down machine 

### ISSUE THREAD

**Issue by fxfactorial** [harmony-one/harmony-ops#383]
...in the report of watchdog

**Comment by Cem-Harmony** [comment]
Is this data stored anywhere? If not, I can have a Map that maps address to shardID, and pass that to a new field in the noReply struct.

#### Will read from Map at these two locations
https://github.com/harmony-one/harmony-ops/blob/afe466e9c19fccf65e477514fd2c669344c57097/monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go#L706-L709
https://github.com/harmony-one/harmony-ops/blob/afe466e9c19fccf65e477514fd2c669344c57097/monitoring/harmony-monitor/blockchain-watchdog/reporting-server.go#L723-L726

I'll have to look into how to populate the Map, respecting concurrency.

**Comment by fxfactorial** [comment]
its all in the summary map, as @janet-harmony
