### ISSUE TITLE
Send out notification to offline node runners

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#39]
Been doing technical supports for our node runners, one common request is that the offline node runners would like to have a prompt (email or sms) notification about offline nodes.

<img width="682" alt="Screen Shot 2019-08-28 at 9 04 17 AM" src="https://user-images.githubusercontent.com/5258417/63878162-df8a7980-c97d-11e9-9de8-7a09737a3187.png">

**Comment by LeoHChen** [comment]
You need to think big.  I am thinking we should provide a docker image for people to have local Grafana running and monitor their node in the remote.  Grafana can be hooked up with a paging mechanism.  This is like a decentralized solution.  I don't like to provide a centralized solution.
