### ISSUE TITLE
Version Upgrade Failure 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#396]
* upgrade to the latest version on s3 branch
* s0 and s2 upgraded without any issue
* caught the following error in the node (`54.161.139.219`) in shard 1

`{"level":"debug","port":"9000","ip":"54.161.139.219","caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:169","time":"2020-02-23T00:47:07.103241694Z","message":"[OnAnnounce] Receive announce message"}
{"level":"warn","port":"9000","ip":"54.161.139.219","error":"unknown ancestor","inChain":"328075","MsgBlockNum":"328139","caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:228","time":"2020-02-23T00:47:07.107628154Z","message":"[OnAnnounce] Block content is not verified successfully"}
{"level":"debug","port":"9000","ip":"54.161.139.219","caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:473","time":"2020-02-23T00:47:07.202920382Z","message":"[OnPrepared] Received Prepared message"}
{"level":"info","port":"9000","ip":"54.161.139.219","MsgBlockNum":328139,"MsgViewID":328161,"caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:501","time":"2020-02-23T00:47:07.207356437Z","message":"[OnPrepared] Received prepared message"}
{"level":"error","port":"9000","ip":"54.161.139.219","error":"unknown ancestor","inChain":"328075","MsgBlockNum":"328139","caller":"/home/ec2-user/harmony/consensus/consensus_v2.go:566","time":"2020-02-23T00:47:07.21072377Z","message":"[OnPrepared] Block header is not verified successfully"}`

**Comment by AndyBoWu** [comment]
Terminated the current rolling upgrade, and restarted the same procedure, but it was not successful.

I had to finally force upgrade all the nodes in shard 1 together. 

http://watchdog.hmny.io/report-testnet#top-of-page

All shards are online and in consensus. They all have the latest version.

The reason for the above error message is unknown.

**Comment by LeoHChen** [comment]
if one node failed, it should be okay to ignore.  One thing I learned is to let it finish if just one node failure, or just restart one node separately. Not necessary to restart the entire process, which is taking to loong.
