### ISSUE TITLE
Inconsistent Results Returned by hmy_getTransactionsHistory API Call

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#402]
Reached out by Vlad, informed me that one api call (`hmy_getTransactionsHistory`) does not return consistent results. 

We are troubleshooting the issue now on the mainnet.

Partner: Trust Wallet

**Comment by AndyBoWu** [comment]
one possible cause is that 1/2 explorers are out of sync, or even the hmy service is offline.

But this is not the case, I just confirmed that
1/ hmy service is onilne for both nodes
2/ both have the lastest height

**Comment by AndyBoWu** [comment]
Neither Vlad or I could not reproduce the results on our side. We tried the same api call with that address, we got consistent results without any issue.

We might need to ask someone else to do this similar test again, may be from the same location where trust wallet partner located.

<img width="1022" alt="Screen Shot 2020-02-25 at 10 25 20 AM" src="https://user-images.githubusercontent.com/5258417/75275536-8af37a00-57b9-11ea-9d11-e774f05e0899.png">

**Comment by mindstyle85** [comment]
@AndyBoWu 

./hmy blockchain account-history one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv --node="https://api.s0.t.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "transactions": [
      {
        "blockHash": "0x4ed9a6c8257791c73a5bba3b131daf804d860357bc3da887b0a1ee7a2af40882",
        "blockNumber": "0x17ba3d",
        "from": "one13vv5kp0kwhrth0xn3duecm43lnzt42sgcv8g8r",
        "gas": "0x5208",
        "gasPrice": "0x3b9aca00",
        "hash": "0xe42368e1886b851b0a2a83a658602588a7cf17b05bb7d684e5ae85b110143297",
        "input": "0x",
        "nonce": "0x70",
        "r": "0x980dccfb562ed6b0a96e1a80fc1bbf89a74fe502729421c6ad8dc9a78e67842c",
        "s": "0x64286dd296e972c51db6684fef3224701a9119cc18fb836f1166a9658f405380",
        "shardID": 0,
        "timestamp": "0x5ddb8f30",
        "to": "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz",
        "toShardID": 0,
        "transactionIndex": "0x0",
        "v": "0x26",
        "value": "0x174876e800"
      },
      {
        "blockHash": "0xb0b21ddd6829f3546926a5e91ebb60b24998d553880b073ff888815ee01d33a4",
        "blockNumber": "0x17ba56",
        "from": "one13vv5kp0kwhrth0xn3duecm43lnzt42sgcv8g8r",
        "gas": "0x5208",
        "gasPrice": "0x3b9aca00",
        "hash": "0x8f696467de66d5b1162250dd17dcae26473734220e127fe15614bca7c4c8d355",
        "input": "0x",
        "nonce": "0x71",
        "r": "0xdd70f3f1206d661f7f17aa88921260664b2a2ff0fb51462b3cb99a51292f36ab",
        "s": "0x479dbd470930d423dc2f15683274a582e255961f78a15d46d456ba185b43d555",
        "shardID": 0,
        "timestamp": "0x5ddb8ffc",
        "to": "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz",
        "toShardID": 0,
        "transactionIndex": "0x0",
        "v": "0x26",
        "value": "0x174876e800"
      },
      {
        "blockHash": "0x45fe5b99e8227f1658a50434bb9532da2c1ebdf3206ab99550a7e6bbdd168051",
        "blockNumber": "0x17ba77",
        "from": "one13vv5kp0kwhrth0xn3duecm43lnzt42sgcv8g8r",
        "gas": "0x5208",
        "gasPrice": "0x3b9aca00",
        "hash": "0x104c06b4ce606affc43b201f8cbaf952f460baab8bd619e586f47acf8f80fba0",
        "input": "0x",
        "nonce": "0x72",
        "r": "0x2101c68673fef209ae73972c7b8d8ffc163501957a337d29095d55970bf67e4f",
        "s": "0x60b0b86d5877f9366a0ef423944d4b7358025e82a3bbdabdc25ddcd6d0e1e53",
        "shardID": 0,
        "timestamp": "0x5ddb910b",
        "to": "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz",
        "toShardID": 0,
        "transactionIndex": "0x0",
        "v": "0x26",
        "value": "0x174876e800"
      }
    ]
  }
}

**Comment by AndyBoWu** [comment]
@flicker-harmony See the above results repored by @mindstyle85

**Comment by mindstyle85** [comment]
for s3:

luka@ubuntu:~/Desktop/devnet2$ ./hmy blockchain account-history one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv --node="https://api.s3.t.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "transactions": [
      {
        "blockHash": "0x6c7ad2a9638723c5b6fa6551a4f1e869501b1a9b06a241bd48d86268bbe9e170",
        "blockNumber": "0x9c418",
        "from": "one1trghegqlxyvkq8suavy6tmhfppcdg4rng3xlct",
        "gas": "0x546c",
        "gasPrice": "0x0",
        "hash": "0x68b8c78320371023f81fa67e42c3742f4aa517b7c96ef8c120a81a34e884f3c7",
        "input": "0x313037303935383136",
        "nonce": "0x0",
        "r": "0xbda69977822f63655efa54e789ecc7eeb66050e1e62c04a49e2584e9c8f93171",
        "s": "0x39691ce060e8319611b0c37269b54aa6ac70bdaca3bfbb6c2d99d43158fe7cfb",
        "shardID": 3,
        "timestamp": "0x5d67978c",
        "to": "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz",
        "toShardID": 0,
        "transactionIndex": "0x0",
        "v": "0x1c",
        "value": "0xde0b6b3a7640000"
      }
    ]
  }
}


for s1:

 ./hmy blockchain account-history one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv --node="https://api.s1.t.hmny.io"
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "transactions": [
      {
        "blockHash": "0x5ecfcf39c0850f03308b2e9ff90aeceae7326cfc326ccaec9726ecaf3ad4daf4",
        "blockNumber": "0x97e4b",
        "from": "one1qtah9p2et4mt7x49xygqfhs2d9hgjvmrek9ppg",
        "gas": "0x5208",
        "gasPrice": "0x0",
        "hash": "0x3a5d9a0c67fd48832ac753f5f843a618941c72a033f15611a22f45a293a27742",
        "input": "0x",
        "nonce": "0x0",
        "r": "0x9db6b55c185f9a518051ca82ae466b4cdfe4d4758d04da7cc25666195977934f",
        "s": "0x6794507de0c24a7af21acfbb2dad90aeff4e7e68eaa8ebd37fedfbd8b4c9d5e1",
        "shardID": 1,
        "timestamp": "0x5d63e401",
        "to": "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz",
        "toShardID": 0,
        "transactionIndex": "0x0",
        "v": "0x1c",
        "value": "0xde0b6b3a7640000"
      },
      {
        "blockHash": "0x086d93334af8291e9bba1575080acb73fac1b931cdf10a18b727ba22a2e765ef",
        "blockNumber": "0x97f88",
        "from": "one1qtah9p2et4mt7x49xygqfhs2d9hgjvmrek9ppg",
        "gas": "0x5208",
        "gasPrice": "0x0",
        "hash": "0x72d4d9b6efc611c127819971e9537669e38d042b7b66ed954481be5e95e212d2",
        "input": "0x",
        "nonce": "0x1",
        "r": "0x546dc7edf49115350617d08bd83c072e3de5394ac61ef1692a65cde4bd9109f5",
        "s": "0x3e8b8060f1c85e63d65d88524b78b3ebcb7b54ae0d622bd6d4ce5d29e1b90373",
        "shardID": 1,
        "timestamp": "0x5d63ee2e",
        "to": "one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz",
        "toShardID": 0,
        "transactionIndex": "0x0",
        "v": "0x1c",
        "value": "0xde0b6b3a7640000"
      }
    ]
  }
}




s2 is empty

**Comment by AndyBoWu** [comment]
@mindstyle85 I think you should use api call for `TransactionsHistory`

**Comment by flicker-harmony** [comment]
@mindstyle85 what is one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz address

**Comment by mindstyle85** [comment]
@AndyBoWu ah, @Daniel-VDM asked if we can check with the hmy, will do an api call too..

@flicker-harmony that address usually got in when the address you type in is wrong, i remember this from testing, and if the one1 address structure was wrong it gave out one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz

**Comment by flicker-harmony** [comment]
@mindstyle85 hmy cli returns incorrectly. How it could return tx with from one1qtah9p2et4mt7x49xygqfhs2d9hgjvmrek9ppg and to one1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqquzw7vz when both are NOT one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv

**Comment by mindstyle85** [comment]
yeah agreed, hmy doesnt work correctly here, just getting set to try the rpc call

**Comment by BrunoMarshall** [comment]
yes, got the same thing : 
![image](https://user-images.githubusercontent.com/35432495/75280935-a341b400-580e-11ea-80de-e059f3a5c664.png)

**Comment by mindstyle85** [comment]
from rpc call:


{
    "jsonrpc": "2.0",
    "id": "hmy_getTransactionsHistory",
    "result": {
        "transactions": [
            {
                "blockHash": "0xe6e65f0f9f1e694d93012f1f2b4713cdd253cc6a15e729ff6df23a78d7694013",
                "blockNumber": "0x1b2cd7",
                "from": "one1syjs6cnfwd9fgrhng03dyzs07suwtywwreczmk",
                "timestamp": "0x5df7cb24",
                "gas": "0x33450",
                "gasPrice": "0x3b9aca00",
                "hash": "0x391af85c5e25ee96cbbc417121b6bacc0ed466c0423467354192c075444e7603",
                "input": "0x",
                "nonce": "0x1f",
                "to": "one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv",
                "transactionIndex": "0x0",
                "value": "0x1bc0ae68df60e000",
                "shardID": 0,
                "toShardID": 0,
                "v": "0x25",
                "r": "0xb65b59fd1c9733977b0689e07a1869713ae2b2f8eabecee0a426c3f7fe62ac6b",
                "s": "0x52b5be00be05173d89ffbf82a47b03f50268e6fe1ccd36a3fa7123a5255d2be2"
            },
            {
                "blockHash": "0x1b45da220f94f41bd42dc0eb89a5e83ce77b37cc78dbc9032bd10a5bbab13674",
                "blockNumber": "0x1b2cdb",
                "from": "one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv",
                "timestamp": "0x5df7cb45",
                "gas": "0x33450",
                "gasPrice": "0x3b9aca00",
                "hash": "0x6bfd003239bf137855342f6266c456ae1b342e886bd1965a47edd4c74dd1a687",
                "input": "0x",
                "nonce": "0x0",
                "to": "one1syjs6cnfwd9fgrhng03dyzs07suwtywwreczmk",
                "transactionIndex": "0x0",
                "value": "0x1bbfef6a6ff9c000",
                "shardID": 0,
                "toShardID": 0,
                "v": "0x26",
                "r": "0x44c2a7b8c38612a3ce8b51967947c0c9756dda8d82d0f12137451ce33bbef390",
                "s": "0x34234c6c26fe36bda246db845692fd248cb4060cda0d1c6056298b39486ed4f2"
            },
            {
                "blockHash": "0x58cc90d1b9302d0121b426f5fd35014acbc009defe36c5bbff6ac920d6005526",
                "blockNumber": "0x1b2cf2",
                "from": "one1syjs6cnfwd9fgrhng03dyzs07suwtywwreczmk",
                "timestamp": "0x5df7cc02",
                "gas": "0x33450",
                "gasPrice": "0x3b9aca00",
                "hash": "0xf54f6f86df1624f38fcedf56eb248854a13a733e0b0f92d4b31b9cc7196d90b0",
                "input": "0x",
                "nonce": "0x20",
                "to": "one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv",
                "transactionIndex": "0x0",
                "value": "0x1bc0ae68df60e000",
                "shardID": 0,
                "toShardID": 0,
                "v": "0x25",
                "r": "0x46d14df06948f055e519ac244bcaaa3c3446ed20671d41db01546ddaad32503b",
                "s": "0x50d13aeb94f2e8c760723afa4d892f3ca17690451a57465ea7e39c5d347efe8"
            },
            {
                "blockHash": "0xa84376f0f4d082b76355ccc6ec491660c0062d9ef3f39985ca00986e8dcbacc1",
                "blockNumber": "0x1b2d1b",
                "from": "one1e4mr7tp0a76wnhv9xd0wzentdjnjnsh3fwzgfv",
                "timestamp": "0x5df7cd50",
                "gas": "0x33450",
                "gasPrice": "0x3b9aca00",
                "hash": "0x73355f625d0f7ef31512657c0f669e710c8c91a67180cd28bc919cfca0a2af82",
                "input": "0x",
                "nonce": "0x1",
                "to": "one1syjs6cnfwd9fgrhng03dyzs07suwtywwreczmk",
                "transactionIndex": "0x0",
                "value": "0x1bc09b4f6dd69000",
                "shardID": 0,
                "toShardID": 0,
                "v": "0x26",
                "r": "0xf31271b93e446bce8cc83eb997183146b4da2378a5f2cb1fc4ae64fbd65a93f5",
                "s": "0x77e8e5693a87394204f96693a15f2157459b0329a2ddab97da0bf1cfb6fbce8c"
            }
        ]
    }
}

**Comment by flicker-harmony** [comment]
@mindstyle85 same stuff

**Comment by mindstyle85** [comment]
yeah looks the same as yours.. however looks like the hmy calls are broken? @flicker-harmony

**Comment by flicker-harmony** [comment]
@mindstyle85 yep, but I didn't work on that code, someone needs to fix this for hmy cli

**Comment by mindstyle85** [comment]
ok, will open up an issue for that in the go-sdk @flicker-harmony

**Comment by AndyBoWu** [comment]
@mindstyle85 then we got the same results on our end, consistently. K!!

**Comment by AndyBoWu** [comment]
Another bug caught by @mindstyle85 : https://github.com/harmony-one/go-sdk/issues/153

**Comment by AndyBoWu** [comment]
INVALID I think. Vlad and I are not able to reproduce this result on Postman.
