### ISSUE TITLE
Launch a Separate Explorer Node for Token Unlocking Query 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#405]
Deploy this fix on the explorers on LRTN for CoinGecko.

https://github.com/harmony-one/harmony/pull/2306

`commit fc614e4fa75284be5c840acc456007344fa8e229`

**Comment by AndyBoWu** [comment]
confirmed with John, RJ, Edgar, this is NOT feasible atm to wipe off all DB on LRTN.

**Comment by AndyBoWu** [comment]
instance name: harmony-ops-405

**Comment by AndyBoWu** [comment]
Current version

`Harmony (C) 2020. harmony, version v5595-master-20191208.0-218-g380449bb (ec2-user@ 2020-02-25T19:58:57+0000)`

**Comment by AndyBoWu** [comment]
`
commit 380449bbf7a2db9e62fff9a75ede367846ff5cfc
Author: Edgar Aroutiounian <edgar.factorial@gmail.com>
Date:   Tue Feb 25 11:28:29 2020 -0800

    [reward] Increase percision on percentage in schedule (#2306)
`

**Comment by AndyBoWu** [comment]
Versoin downloaded from master branch

```
[ec2-user@ip-172-31-72-92 staging]$ LD_LIBRARY_PATH=. ./harmony -version
Harmony (C) 2020. harmony, version v5595-master-20191208.0-218-g380449bb (jenkins@ 2020-02-25T20:15:22+0000)

```

**Comment by LeoHChen** [comment]
@fxfactorial , if this change is needed for mainnet, it has to be cherry-picked to s3 branch.

**Comment by AndyBoWu** [comment]
node launched. Doing testing with RJ and Edgar.

**Comment by AndyBoWu** [comment]
```
enabled rpc
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "12600000000.000000000000000000"
}
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "4977696588.235282800000000000"
}.


```

**Comment by AndyBoWu** [comment]
dns name created `one.supply.hmny.io`

But there is some known delay for Route 53 to populate this record to all name servers.

**Comment by AndyBoWu** [comment]
Andy | HarmonyToday at 3:18 PM
@Nikos the new endpoint is: http://supply.hmny.io:9500/
two RPC calls are still: hmy_getTotalSupply   hmy_getCirculatingSupply

**Comment by AndyBoWu** [comment]
https://github.com/harmony-one/harmony/pull/2318

**Comment by AndyBoWu** [comment]
<img width="776" alt="Screen Shot 2020-02-27 at 12 46 11 PM" src="https://user-images.githubusercontent.com/5258417/75485415-84066c00-595f-11ea-9ca0-55a6604a05b0.png">
<img width="776" alt="Screen Shot 2020-02-27 at 12 45 52 PM" src="https://user-images.githubusercontent.com/5258417/75485421-85d02f80-595f-11ea-922b-1112255d0d8b.png">
