### ISSUE TITLE
Amazon EC2 Instance Retirement

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#44]
5 in total, they are:

(instance-ID: i-02da31bb79757709b) in the us-west-2 region
(instance-ID: i-00d3acf938c7f8520) in the us-west-2 region
(instance-ID: i-058e4758c92d0a955) in the us-west-2 region
(instance-ID: i-091232c0b9f84ef02) in the us-west-2 region
(instance-ID: i-0980e4873f3764c84) in the us-west-2 region

**Comment by AndyBoWu** [comment]
These 5 instances have been cleaned up.

**Comment by LeoHChen** [comment]
have you launched new one to replace them, or not needed?

-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by xChickens** [comment]
![image](https://user-images.githubusercontent.com/2402510/64059180-cfd08800-cb6b-11e9-986b-f2fe8648a733.png)
All cl-test instances.
