### ISSUE TITLE
[Monitoring] Add monitoring on the last continuous crosslink in beacon chain

### ISSUE THREAD

**Issue by rlan35** [harmony-one/harmony-ops#463]
We need to monitor the last continuous crosslink on beacon chain to make sure the cross-link is working.

This will need a new RPC to expose the data. The data can be read from DB in beacon chain using "ReadShardLastCrossLink".

We need to monitor that for all shard chains.

**Comment by rlan35** [comment]
is the crosslink monitoring live in watchdog?

**Comment by janet-harmony** [comment]
Yup, it's up.
PagerDuty if no cross links processed in 10 minutes.

**Comment by rlan35** [comment]
We should also report the latest crosslink for each shard in watchdog.

**Comment by janet-harmony** [comment]
Added display for last cross link on & deployed.
