### ISSUE TITLE
Suppress the Y/n prompt to action to clean up old DB and logs

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#484]
$ ./node.sh
   -y             run in legacy, foundational-node mode (default)
   -Y             verify the signature of the downloaded binaries (default: off)

./node.sh -S -c -z -I -N staking -k d3...key
Remove old database/logs? (Y/n)

Li | Harmony.oneToday at 9:31 PM
that's a nice optimization, so that you can run the command and leave your tmux right away

**Comment by AndyBoWu** [comment]
easy fix, but need to consider potential OPS risks involved.

**Comment by LeoHChen** [comment]
so the request is to no prompt of Y/n?  sure.  We can use -Y to ignore the prompt.  However, we need to find another flag for verification.  Maybe we shall clean up some options.  -Y is not currently used.

**Comment by AndyBoWu** [comment]
https://github.com/harmony-one/harmony/pull/2535

**Comment by AndyBoWu** [comment]
will test it out tmr either by myself, or with John.
