### ISSUE TITLE
http://explorer2.harmony.one/ Does not Load at all

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#49]
One of the possible reasons is that the SSL certificate has expired.

**Comment by lzl124631x** [comment]
Updated the cert for explorer2. But note that the explorer nodes for explorer2 haven't been working for a while, so the explorer can't retrieve any data.

**Comment by LeoHChen** [comment]
there is no explorer node for explorer2. @Andy Wu <andy@harmony.one> ,
please just use leader node as the explorer node and send the data to
explorer2 backend.

-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>
