### ISSUE TITLE
one click harmony validator node

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#533]
To help new node runners experience the staking node on OSTN, we can develop a one click/script deployment of harmony node.

Based on the docker image for sentry node, we can do the following enhancement.

1) auto generate blskey/pass and used it for staking, create validator, edit validator, etc.
2) just ask user to provide private key or keyfile of the account

**Comment by Daniel-VDM** [comment]
Done with the initial version here: https://github.com/harmony-one/harmony-ops/tree/master/devops/auto_node 

Also wrote a quick guide on how to use it here: https://gist.github.com/Daniel-VDM/fe15ccd0561ba23ef7e0007b33b08d8f
