### ISSUE TITLE
TASK | Reset a Network and Deploy Latest Version 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#550]

**Comment by AndyBoWu** [comment]
we will put all shell scripts reserved for Jenkins job here: `/home/ec2-user/experiment-deploy/pipeline/jenkins` on devops instance.

**Comment by AndyBoWu** [comment]
shell script for this job: `jenkins_reset_deploy_network.sh`

**Comment by LeoHChen** [comment]
https://jenkins.harmony.one/view/TestNet/job/testnet-build-release/
