### ISSUE TITLE
Update Leader Info on /1h

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#552]
on this website: https://harmony.one/1h

All leaders are showing offline while the actual situation is that leaders have been changed to another node. Please update this info.

The detailed procedure is on DevOps Runbook, but do LMK if you have any questions.

**Comment by AndyBoWu** [comment]
Either you can use cmd to find the leader for each shard, good practice to get your hands dirty on the tooling and devops instance, or you can grab the leader info from watchdog.  LMK if you need any help. Thx.

**Comment by ivorytowerdds** [comment]
https://harmony.one/1h leaders are online now

**Comment by AndyBoWu** [comment]
good job. can you close this ticket, @ivorytowerdds ?

**Comment by ivorytowerdds** [comment]
sure! @AndyBoWu
