### ISSUE TITLE
Migrate All 4 Sentry Nodes to Other Cloud Platforms

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#558]
Per LC's suggestion, time to take advantage of our cloud credits.

We are thinking to move all 4 sentry nodes to other cloud platforms, IBM or Azure, to save some cost.

**Comment by AndyBoWu** [comment]
Per discussion and request from @LeoHChen , and information I got from @NiteeshHarmony, we got lots of cloud credits from MS. Once again, kudios for the efforts from @NiteeshHarmony .

@jhd2best , Let's migrate the 4 sentry nodes to MS Azure next week using a TF script. 

Le'ts chat tonight.

**Comment by AndyBoWu** [comment]
notes to @AndyBoWu , need to have azure account asap.

**Comment by jhd2best** [comment]
it is similar as https://github.com/harmony-one/harmony-ops/issues/582, so close it
