### ISSUE TITLE
Grafana monitoring of OSTN and STN

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#559]
use grafana to monitor OSTN and STN with node_exporter exposed data.

Need to create separate dashboard for OSTN and STN.

**Comment by AndyBoWu** [comment]
==== SUBTASK =====

1. https://github.com/harmony-one/harmony-ops/issues/560

**Comment by LeoHChen** [comment]
http://monitor.harmony.one:3000/d/-wELIYjWz/harmony-nodes-monitoring-ostn-shard-0?orgId=1

**Comment by LeoHChen** [comment]
http://monitor.harmony.one:3000/d/OxzUSLjZz/harmony-nodes-monitoring-stn-shard-0?orgId=1
