### ISSUE TITLE
Pagerduty integration with Grafana

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#560]
Currently, our Grafana server sent alerts to discord channel to alert on disk usage.  The alert can be sent to pagerduty.  Also, we need to enable the monitoring of memory usage to check on the OOM issue.

Pagerduty integration can be done via CURL request anyway.  Please talk to Janet on how to trigger a pagerduty alert.

**Comment by AndyBoWu** [comment]
Integrated with Discord, need to integrate with Pagerduty too.
