### ISSUE TITLE
Shard 0..2 showing Offline in /1h and /balances Websites

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#57]
Happened before, the root cause is that the IP addresses of leaders got changed. I can fix the issue again, but the real question is how often does the leader got rotated. And, how can we automate this process.

**Comment by AndyBoWu** [comment]
Related to https://github.com/harmony-one/harmony-ops/issues/50

**Comment by AndyBoWu** [comment]
<img width="837" alt="Screen Shot 2019-09-06 at 10 04 35 AM" src="https://user-images.githubusercontent.com/5258417/64447009-2f102a00-d08f-11e9-80c3-8e92d52b907d.png">
<img width="808" alt="Screen Shot 2019-09-06 at 10 14 51 AM" src="https://user-images.githubusercontent.com/5258417/64447013-30d9ed80-d08f-11e9-9f8d-0b3bb91222a4.png">

**Comment by AndyBoWu** [comment]
QUESTIONS TO PONDER
* how to calculate when the EPOCH changes for each shard

**Comment by xChickens** [comment]
If you have r3 logs downloaded, it's this command:

```head -4 logs/r3/distribution_config.txt | while read -r ip junk; do
./node_ssh.sh -d logs/r3 -o -n "$ip" 'TZ=PST8PDT date --date @$(($(date
+%s) + ([block height]-$(jq -c '\''select(.message == "[TryCatchup] Adding
block to chain") | .myBlock'\'' <
../tmp_log/log-20190628.153354/zerolog-validator-*-9000.log | tail -1)) *
8))'; done
```

Make sure to change [block height] with 2^14*20+epoch

**Comment by AndyBoWu** [comment]
These shards were indeed offline, and we just recovered them.

The root cause might be that we didn't update the node.sh file for terraform launched nodes in the last rolling upgrade.

Also
* Need to add a ticket about how to restart a shard in the DevOps Run book
* The log location is different for legacy nodes (~/../tmp_log/) and terraform launched nodes (~/latest/). So, need to modify the cmd to find `HOORAY` and `BINGO` keyword
