### ISSUE TITLE
JENKINS | Create a pipeline to reset an Internal network

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#574]
Per LC's request.

https://gist.github.com/LeoHChen/f2ba466b60b7443f0cb9cf5102ada475

**Comment by AndyBoWu** [comment]
Subtask: add support to mkeys network for pipeline testing.

**Comment by AndyBoWu** [comment]
[wip] https://docs.google.com/document/d/1Xfrie2AxPZKh0Aq-kiF8ABeIFDPkUNWxwJ4sQRauu4E/edit#

**Comment by LeoHChen** [comment]
https://jenkins.harmony.one/view/TestNet/job/do-hard-reset/
