### ISSUE TITLE
Azure | Terraform to Launch a HMY Node

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#578]
**Documentation**

[wip] https://docs.google.com/document/d/155BiWOnnA9kfpI0y4dSWXDCCbiHqIINvTlieFUYo2AM/edit#

**Comment by AndyBoWu** [comment]
**Subtask**

1/

**Comment by jhd2best** [comment]
it is similar as https://github.com/harmony-one/experiment-deploy/issues/291, so close it
