### ISSUE TITLE
[sentry] deploy 2 sentry nodes for mainnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#582]
Sentry 2 and Sentry 3 on shard 2 and shard 3 are down due to their AWS instances were terminated.  We need to deploy two new nodes, on Azure to continue serving as the sentry nodes for mainnet.

**Comment by LeoHChen** [comment]
I have the bls keys for the sentry nodes. Please check with me if you start to work on this ticket.

**Comment by jhd2best** [comment]
already deploy it, tf script updated see PR:https://github.com/harmony-one/experiment-deploy/pull/320
