### ISSUE TITLE
Kernel tuning on internal node deploy & machine restart

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony-ops#585]
We need to add kernel tuning for all nodes that are deployed on mainnet. (i.e through TF). 

Moreover, we need to make sure that these tunes are still applied after the machine restarts. 

Tunes can be found [here](https://github.com/harmony-one/harmony/blob/master/scripts/node.sh#L71-L139).

The suggestion is to have config under `/etc/conf`

Reference issue https://github.com/harmony-one/harmony/issues/3025

**Comment by jhd2best** [comment]
already checked `sysctl -w` is temporary, not applied after the machine restarts. i will make an Ansible script to update kernel tuning by modify `/etc/sysctl.conf`

**Comment by jhd2best** [comment]
optimize the Ansible script. see PR:https://github.com/harmony-one/experiment-deploy/pull/352
