### ISSUE TITLE
node auto recovery

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#589]
sometimes our AWS node may be terminated due to capacity issues as we are using spot instance.  We can auto-detect this issue in watchdog, however, right now, we need manual work to launch a new node to restore it.

We can set up a Jenkins job to check the uptimerobot pagerduty API, once we detected the node is offline due to it was terminated, we can launch a new node from mainnet op host. Then update the nodedb, and uptimerobot with the new node's IP.

**Comment by LeoHChen** [comment]
This will save our on-call eng's work to launch the new node for recovery. 

There are a few points need to be careful.
1) the node could be rebooted, but not terminated, we need to query AWS API to determine if the instance was really terminated.
2) auto ack/resolve the pagerduty
3) update uptimerobot with the new IP

**Comment by jhd2best** [comment]
already launched in our Jenkins
