### ISSUE TITLE
upgrade node_exporter to 1.0.1

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#590]
https://github.com/prometheus/node_exporter/releases

upgrade to the latest release of node_exporter 1.0.1, there are some breaking changes, be careful, please.

**Comment by LeoHChen** [comment]
please test and deploy the new node_exporter to mainnet nodes.

**Comment by jhd2best** [comment]
all mainnet nodes already updated to latest node_exporter version(1.0.1)
