### ISSUE TITLE
monitors of all public services

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#593]
Let's create monitors to monitor all public-facing services using uptimerobot.

Here is the list of all public services and owners.
https://www.notion.so/harmonyone/Harmony-Services-and-Owners-6f46704007a24e61a7c0ec38b692b311

For uptime robot, we can set up a dedicated status page for public services, like https://status.harmony.one shall be used for all nodes though.

We shall also set up a new pagerduty service to page individual owners.

**Comment by jhd2best** [comment]
TODO list:
- [ ] set up public service monitor in uptimerobot
- [ ] split internal mainnet node and public service to different notification channel
- [ ] set up a dedicated status page for public services
- [ ] special assign to individual owner for public services in Pagerduty

**Comment by jhd2best** [comment]
dedicate status page for public services launched at `https://service.status.harmony.one`
