### ISSUE TITLE
stop using node.sh in all mainnet nodes

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#595]
myip.opendns.com is not available to use now, it will stop node.sh from running due to the ip checking failure.

Now it is time to stop using node.sh on harmony's mainnet nodes. Instead, we can just run `harmony` binary directory in systemd service.

The command to use is `harmony --run.legacy --http.ip 0.0.0.0`

Please update all harmony.service file on all nodes, to use harmony binary directly.

Also, our terraform scripts need to be updated for this change as well.

Noted, on GCP node, I've noticed sometimes harmony is failed to start in systemd because the selinux prevent the user process from running.  Need to disable selinux permanently on those nodes and disable selinux in current running process.

**Comment by mindstyle85** [comment]
@LeoHChen just to notify.. there are a lot of users that still use node.sh and didnt/dont want to go to using the binary yet. Wht is the solution for them, other than going to the binary?

**Comment by jhd2best** [comment]
all validator node(except explorer and leader) already change to use binary on AWS and GCP. will change explorer node now

**Comment by jhd2best** [comment]
all explorer node already change to use binary

**Comment by jhd2best** [comment]
pushed change node to start by binary Ansible script. see https://github.com/harmony-one/ansible/pull/6

**Comment by LeoHChen** [comment]
> @LeoHChen just to notify.. there are a lot of users that still use node.sh and didnt/dont want to go to using the binary yet. Wht is the solution for them, other than going to the binary?

node.sh will be depreciated. @mindstyle85 thanks for the inquiry.  Can you lead a community discussion and proposal on the retirement of node.sh?

**Comment by LeoHChen** [comment]
looks good @jhd2best , have you made changes on the terraform scripts?

**Comment by jhd2best** [comment]
pushed change node to start by binary Terraform script. see https://github.com/harmony-one/terraform/pull/5

**Comment by LeoHChen** [comment]
nice work

**Comment by LeoHChen** [comment]
we can do the leader update tonight. @jhd2best

**Comment by LeoHChen** [comment]
Fixed `node.sh`, https://github.com/harmony-one/harmony/pull/3403

**Comment by LeoHChen** [comment]
node.sh deprecation proposal https://talk.harmony.one/t/node-sh-deprecation/949

**Comment by jhd2best** [comment]
all leader node changed successful
