### ISSUE TITLE
replace jenkins release job with github action

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#597]
We are using a release job on our jenkins server for harmony node release.  Since we are doing github release to publish the artifact now, we shall use github actions to do the release.

The expected workflow is like the following, my initial ideas,

- we create a release tag and push to the release branch or `main` branch
- we create a new release using the published tag
- the github action will kick in
  - check out the source code
  - build the static binary on both linux (first priority) and mac os platform (secondary)
  - build docker image of the release binary to dockerhub
  - publish the static binary to the release page

**Comment by LeoHChen** [comment]
a good github action tutorial can be found here, https://www.youtube.com/watch?v=R8_veQiYBjI

**Comment by jhd2best** [comment]
done. see PR: https://github.com/harmony-one/harmony/pull/3486
