### ISSUE TITLE
modify pushgateway to limit the access of 'delete' function.

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#600]
The current pushgateway website we setup https://gateway.harmony.one has a `delete group` button that allows anyone to delete a group of metrics. Since the metrics data will be resent by the validator to the gateway every minute, we don't have to worry too much about losing the group. However, it is still annoying if ppl accidentally deleted a group of metrics.

So the request is to add certain protection/authentication to delete group function, so that anonymous visitor won't be able to delete the group of metrics w/o authorization.  However, the post/get API calls should still be available to public to use without authorization needed.

**Comment by jhd2best** [comment]
already added permission for `delete group` operate.
