### ISSUE TITLE
scale down aws instances

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#601]
after monitoring the usage/cpu of our ec2 instances, I think we can scale down quite a few of the instances.

1) all the bootnodes can be launched using t3.micro instead of t3.small/t3.medium using the same elastic IP.
2) staking dashboard can be scaled down to t3.small install of c5.large.
3) all bridge backend/frontend including mainnet/testnet can be scaled down to t3.micro instead of t3.medium.

Please make sure no service interruption during the migration process.

**Comment by jhd2best** [comment]
instance for `staking dashboard` already change to `t3.small`

**Comment by jhd2best** [comment]
instances for `bootnodes` already change to `t3.micro`

**Comment by jhd2best** [comment]
instances for `mainnet bridge backend/frontend` already change to t3.micro. testnet temporarily not changed until hackathon 
 end, because instance will crash if there is no need resource before.
