### ISSUE TITLE
replace all aws c5 instance with lightsail node

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#602]
after we rollout the 2s finality, it seems okay to replace all aws c5 instances with the lightsail nodes to save the transfer cost. let's do it gradually one by one in 2021.  The shard0 leader node, with index 0 may still remain c5.large as it is almost the most heavy loaded node.  We still need to make sure CPU is no longer the bottleneck of the consensus.

**Comment by jhd2best** [comment]
done
