### ISSUE TITLE
new stable testnet: devnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-ops#607]
we need to start a new stable testnet for dApp developers, One shard is good enough.

**Comment by mirrormirage0** [comment]
Steps

1. Update the references of pangaea in the following files. (1 shard, with domain d.hmny.io )

- https://github.com/harmony-one/harmony/blob/main/internal/configs/sharding/pangaea.go
- https://github.com/harmony-one/harmony/blob/main/internal/params/config.go
- https://github.com/harmony-one/harmony/blob/main/internal/configs/node/network.go
- https://github.com/harmony-one/harmony/blob/main/internal/configs/node/group.go

2. Handover of new sub-domain d.hmny.io to P-OPS for devent RPC/API.
3. Use Testnet BLS keys
4. Setup required VPS

**Comment by sophoah** [comment]
devnet has been launched
