### ISSUE TITLE
Recover Offline Nodes on Sep 7, 2019

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#62]
INCIDENT #861

**Comment by AndyBoWu** [comment]
`restart harmony process (y/n)?y
Sat Sep 7 18:51:53 UTC 2019 : can't find benchmark config file : /home/ec2-user/experiment-deploy/configs/benchmark-r3.json . Exiting ...`

**Comment by AndyBoWu** [comment]
![Screen Shot 2019-09-07 at 11 58 25 AM](https://user-images.githubusercontent.com/5258417/64479091-d6ac5b80-d166-11e9-8efe-fc9350fb78fc.png)

**Comment by AndyBoWu** [comment]
Root cause: no more disk space available. 

* Need to extend EBS volume ASAP for that instance
* Maybe also check if any large log files consume too much space?

**Comment by LeoHChen** [comment]
have you checked if we need to remove any backup directory?

-----
Leo Chen

work hard, dream big, make history.
culture <https://harmony.one/culture>, team <https://harmony.one/team/>,
deck <https://harmony.one/deck>, roadmap <http://harmony.one/roadmap>,
vision <https://harmony.one/xoogler>, research
<https://harmony.one/research>, whitepaper <https://harmony.one/whitepaper>,
code <https://github.com/harmony-one/harmony>, annual-letter
<https://harmony.one/annual-letter>, newsletter <https://harmony.one/news>,
overview <http://harmony.one/overview>, binance-report
<https://harmony.one/binance-report>

**Comment by AndyBoWu** [comment]
Yes, I removed a few *.oops files, and some compressed files from the home folder. Now the instance still has 13 GB of free space.

**Comment by AndyBoWu** [comment]
Have been working on the node for a while, after a few attempts, we were still not able to recover the node.

Then we decide to launch a new node using Terraform to replace the previous node. Node launched successfully. Also run the script to update this node in Uptime.

**Comment by AndyBoWu** [comment]
Adding this process to the DevOps runbook.

**Comment by AndyBoWu** [comment]
Also, located instance from the distribution_config.txt file, and terminated this instance to save some cost.
