### ISSUE TITLE
Node Launched by TF 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#80]
<img width="652" alt="Screen Shot 2019-09-12 at 12 14 32 PM" src="https://user-images.githubusercontent.com/5258417/64814045-89116380-d557-11e9-9cc4-ff6dff820a9c.png">

@LeoHChen Not sure how the last a few lines were get added into the distribution_config file, but this might create some consistency issue in the long run.

**Comment by LeoHChen** [comment]
Those few nodes were launched by me initially to replace retired nodes. Please fix the name of those node to make it more consistent.
