### ISSUE TITLE
Deploy Node Exporter on TF Launched Nodes

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#85]
TASK 1: deploy node exporter on TF launched nodes

and 

TASK 2: update current TF script to have node exporter included

**Comment by LeoHChen** [comment]
https://github.com/prometheus/node_exporter/releases/tag/v0.18.1

Update node_exporter to the latest release.

**Comment by AndyBoWu** [comment]
PIPELINE:
* store the deployment script on a public s3 folder
* fetch the script from a test TF node
* execute the file

Expected result:
node exporter is up and running after the installation, and we could see it on the Grafana dashboard.

**Comment by LeoHChen** [comment]
Don't forget to update tf script in aws.1 directory in experiment-deploy.

**Comment by AndyBoWu** [comment]
@LeoHChen Thanks for the reminder. 

This is a blocker for https://github.com/harmony-one/harmony-ops/issues/121

**Comment by AndyBoWu** [comment]
PR submitted to install node exporter on the existing TF nodes. Now working on the part to the TF script to pre-install node exporter.

**Comment by AndyBoWu** [comment]
Documentation: https://docs.google.com/document/d/1_WP-l45Jp3JLOmrGUSRdOEpJ74QnZZKjsyWRnmEKwfI/edit
